openpathsampling/openpathsampling

devtools/ci/index.html, devtools/ci/push-docs-to-s3.py, devtools/conda-recipe/meta.yaml
This PR does the following:
* Updated conda recipe name to `openpathsampling`
* Updated S3 bucket name to `openpathsampling.org`
Once merged, this should allow you to view the docs from http://openpathsampling.org and successfully grab conda packages from the `omnia` binstar.
=> Update S3 bucket name and binstar package name

docs/_themes/sphinx_rtd_theme/static/css/ipynb.css, docs/examples/index.rst
Previous CSS used smallcaps for anything marked `code` in the Markdown cells of IPython notebooks. This made it (1) look different from the actual code cells; (2) look different from inline code in the rest of the sphinx docs; (2) look really ugly when there were many inline references to things from main code blocks (see the "Example trajectories for these ensembles" in http://openpathsampling.org/latest/examples/sliced.html for an example).
This fixes that. Also replaces one header MDTraj->OpenPathSampling.
=> Docs: No small caps in ipynb inline code

devtools/ci/ipythontests.sh, devtools/ci/nosetests.sh
I think this will make a small improvement as an addendum to #145 : previously the `ipythontests` stopped after the first failure. Better to run all the notebooks and see if anything else fails.
=> Should allow all tests in subscript to run

examples/ipython/storage_fastquery.ipynb, openpathsampling/chainableobjectdict.py, openpathsampling/storage/query_store.py
Due to the new netCDF sorted indices requirement I had this fixed, but apparently my test was not able to see, that the back-ordering after requesting from the netCDF file to the original index order was permuting in the wrong direction. This one fixes it.
=> Important FIX: Wrong order or orderparameters

examples/ipython/debug_logging.conf, openpathsampling/ensemble.py, openpathsampling/tests/testensemble.py
This fixes a weird bug where the order of a combination mattered when used with a SeqEns. Example of the problem, assuming you've set up a reasonable `bigvol` and length==1 `traj`:
```python
vol_ens = paths.AllInXEnsemble(bigvol)
len_ens = paths.LengthEnsemble(5)
combo1 = vol_ens & len_ens
combo2 = len_ens & vol_ens
seq1 = paths.SequentialEnsemble([combo1])
seq2 = paths.SequentialEnsemble([combo2])
print vol_ens.can_append(traj)
print len_ens.can_append(traj)
print combo1.can_append(traj)
print combo2.can_append(traj)
print seq1.can_append(traj)
print seq2.can_append(traj)
```
All of these should print `True`. However, the last one was printing `False`.
The bug appears to be that our short-circuit logic used `is True` instead of `== True`. In particular, the line in …
=> Fix for SeqEns([A & B]) != SeqEns([B & A]) bug

examples/ipython/fast_sample_loading.ipynb, openpathsampling/storage/object_storage.py, openpathsampling/storage/sample_store.py
This adds a function to cache all samples at once instead of loading them one by one.
In particular for samples this is verz effective since samples contain not too many complex information.
Just to load Samples the new function is 2-3 orders faster than the old method.
See example NB for comparison.
=> Load samples fast

examples/ipython/alanine.ipynb, openpathsampling/openmm_engine.py, openpathsampling/pathmover.py, openpathsampling/snapshot.py, openpathsampling/storage/snapshot_store.py, openpathsampling/tests/test_helpers.py, openpathsampling/tests/teststorage.py, openpathsampling/trajectory.py
This will add that Snapshots are created in pairs. Each Snapshot and it's reversed one. 
This allows us to handle multiple reverses of snapshots to be identified as the same.
```
snapshot.reversed.reversed = snapshot
```
This requires to use
```
snapshot.reversed
```
to get the reversed snapshot. Not sure if we really want to use this. But that fixes the problem @dwhswenson had.
Last,
```
reversed(traj)
```
will return an iterator that runs in reversed order over reversed snapshots. So to get a reversed trajectory we can write
```
Trajectory(list(reversed(traj)))
```
or just
```
for reversed_snap in reversed(traj):
```
=> [WIP] add paired Snapshots and trajectory improvements

openpathsampling/tests/testensemble.py
We'd recently been getting occasional errors in `test_ensemble`. This PR fixes that.
In a test before this fix, I got errors 12/100 runs of `nosetests test_ensemble.py`. After this fix, 0/100.
The problem was in the way the test trajectories were built. For simplicity, early on I made test trajectories as lists of numbers instead of lists of snapshots. However, this created problems in certain parts of the code, because two "snapshots" in this fake trajectory list could have the same value, and the caching behavior assumes that snapshots never repeat in the trajectory.
The change makes the tests run a little slower (getting an order parameter from a snapshot is more expensive than reading a number from a list of them), but at least it's correct and tests pass consistently!
Anyway, this …
=> Fix ensemble testing

openpathsampling/__init__.py, openpathsampling/pathmovechange.py, openpathsampling/pathmover.py
This will mostly cleanup the tree handling of PathMoveChanges. This includes
1. A tree consists of nodes
2. Each node can have zero, one or more children
3. Each child is a node itself
1. The tree structure is given as a nested list.
2. The first element in the list is the head of the node
3. Element 2 to N are the children. This way we can access a child using __getitem__[#child] while [0] get the element of the node
4. Children are always wrapped in brackets
5. The head can be a PathMover instance or PathMoveChange instance or a wildcat
node = [head, [child1], [child2], ... ]
This means that the brackets naturally indicate going down `[` or going up `]` the tree
A tree can be a subtree if the subtree (always starting from the top)
fits on top of the tree to match. Here child nodes are …
=> [WIP] Better Tree Handling for PathMoveChanges

.travis.yml, devtools/ci/after_sucess.sh, docs/requirements.txt
I'm sure @jhprinz also got an email from Travis on this, but the last two merges to master fail on Travis. See:
* https://travis-ci.org/choderalab/openpathsampling/builds/67765284
* https://travis-ci.org/choderalab/openpathsampling/builds/67765398
I'm trying to look into the problem: it only occurs while building the documentation, and it seems to be related to the conda environment that gets set up in the documentation build. At least, the complaint comes from a netcdf import statement, loading the hdf library, after you start running sphinx. Locally, the documentation builds without error for me.
The last successful build is here (for comparison purposes):
* https://travis-ci.org/choderalab/openpathsampling/builds/66374358
This started after the merge of PR #275, but re-checking the …
=> [WIP] Fix Travis docs build

openpathsampling/pathmover.py
The first docstring I looked at was for OneWayShootingMover -- looks like that was actually the only one that @jhprinz hadn't corrected in #278. Anyway, this should be pass tests and be ready for merge.
=> Fixed a couple docstrings

openpathsampling/storage/object_storage.py, openpathsampling/storage/storage.py, openpathsampling/todict.py
This adds a quick fix to update the internal list of storable objects. This will be the same in the new storage.
You can store locally created classes as well provided they are subclassed from `StorableObject` which is the case for all built-in storable OPS objects.
The list is created when a storage file is opened or created. If you define your class after opening a storage file you can call
```
storage.updated_storable_classes()
```
to update the list manually.
Note that classes are stored by class name and so no class names can be the same. Not sure what trouble this will cause. We sould add some testing if a user by accident creates classes that already exist.
=> allow external defined classes to be stored

openpathsampling/analysis/move_scheme.py, openpathsampling/analysis/move_strategy.py, openpathsampling/tests/test_helpers.py, openpathsampling/tests/testmovestrategy.py
Adds the ability to switch between EnsembleHop and ReplicaExchange implementations of ensemble changing. This is a big step toward Single Replica TIS.
***
The approach here is to use the same "group" (repex) for both ensemble hop and replica exchange (although this can be customized in the strategy if the user really wants to). This is where some of the multiple-level stuff about move strategies (see #285). For example, a user can define a certain specific replica exchanges as being important using a `SelectedPairsRepExStrategy`, and then convert those to `EnsembleHop`s using the `EnsembleHopStrategy` -- and, of course, they can be switched back again by the `ReplicaExchangeStrategy`. It doesn't matter the order in which the user adds these strategies to the scheme doesn't matter; the …
=> EnsembleHopStrategy and ReplicaExchangeStrategy

examples/ipython/mstis.ipynb, openpathsampling/pathsimulator.py
Resolves #339 
Now you can set the visualization frequency using, for example:
```python
mstis_calc.visualize_frequency = 50 # redraw every 50 steps
```
This also contain a little hack related to an email @bolhuis sent me earlier, asking about computational cost for different kinds of moves. It turns out, it is easier to get the actual time than the number of MD steps used (still desired; see #292). However, this temporary hack lets you get timings from `step.change.details.timing` (for any step except the first, which doesn't have a mover associated with it anyway).
So,
```python
import numpy as np
repex_timings = np.array(
[s.change.details.timing 
for s in storage.steps 
if s.change.canonical.mover in scheme.movers['repex']]
)
print repex_timings.mean(), repex_timings.std()
``` …
=> visualize_frequency and timing hack

openpathsampling/__init__.py, openpathsampling/analysis/move_strategy.py, openpathsampling/pathmover.py, openpathsampling/tests/testmovestrategy.py, openpathsampling/tests/testpathmover.py
The SRMinusMover is a little different from the standard minus mover: instead of keeping an active minus ensemble, the minus ensemble is only used as an intermediate. 
As before, we define the innermost ensemble, the minus ensemble, and the "segment" ensemble, which is like the innermost except it only allows A->A paths.
The basic process for the single replica minus is like this:
1. Hop innermost->segment
2. Extend segment->minus
3. Select subtrajectory in segment
4. Hop segment->innermost
In practice, this is split into a forward minus and a backward minus: forward minus extends forward and selects final subtraj; backward minus extends backward and selects first subtraj. The total `SingleReplicaMinusMover` has a 50/50 chance of selecting its forward or its backward submover.
So the …
=> Single Replica Minus Mover

examples/ipython/README.md
The links in examples/ipython/README.md were pretty bad. They weren't working, and even if they had been working, the would have pointed to a branch of JHP's fork instead of choderalab/master.
Since GitHub can show notebooks natively, there's no reason to use nbviewer.ipython.org. It also didn't really make sense to use nbviewer for the plain python file.
Quick fix; this should be ready to merge immediately.
=> Correct readme links

.travis.yml, devtools/ci/after_sucess.sh, devtools/ci/install.sh
Miniconda seems to have change its default install path from `~/miniconda` to `~/miniconda2`.
This PR should fix it.
Resolves #354
=> Update miniconda install path

openpathsampling/analysis/network.py
Resolves #361
This was easier than I thought. I just needed to check whether a custom name had been set before renaming stuff to "all states except". 
Ready for review and merge as soon as it passes tests.
=> Fix for state names in 2-state MSTISNetwork

openpathsampling/__init__.py, openpathsampling/analysis/network.py, openpathsampling/analysis/tis_analysis.py, openpathsampling/tests/test_helpers.py, openpathsampling/tests/testnetwork.py
Resolves #360
Current implementation is as version 3 in #360, with classmethods for version 1 (`from_state_pairs`) and version 2 (`from_states_all_to_all`).
Note that, currently, TIS uses the network and transition objects to hold analysis functions as well. None of those are yet implemented for TPSNetworks and Transitions.
Also, this will only have a little bit of testing: I only checked that the desired number of transitions are created. It sounded from email like @bolhuis wanted to use something like this soon, so I wanted to toss something together quickly.
For the most simple TPS network, going from `stateA` to `stateB` (without the reverse process), you can do any of:
```python
versionA = TPSNetwork(stateA, stateB)
versionB = TPSNetwork(initial_states=[stateA], …
```
=> TPSNetwork / TPSTransition

openpathsampling/analysis/move_strategy.py, openpathsampling/tests/testmovestrategy.py
Following @jhprinz's switching of other things to proper AbstractBaseClasses in #375, this does the same for MoveStrategies.
Ready to merge when tests pass.
=> Properly abstract MoveStrategy

openpathsampling/pathmover.py, openpathsampling/visualize.py
This should fix the problems with PathTreeVisualization for now.
It fixes a problem in SamplePathMover that will set the correct index for the trial shooting point.
=> quick fix for visualization bug

docs/examples/mstis.rst, docs/index.rst, examples/ipython/transitions_and_networks.ipynb
=> Documentation updates

openpathsampling/analysis/move_scheme.py
Resolves #418.
Certain attributes for analysis can't be set algorithmically in a `LockedMoveScheme` (in normal schemes, they can be set algorithmically by the `MoveStrategy` objects). If trying to run analysis using a `LockedMoveScheme` without these attributes set, the desired behavior is to raise an `AttributeError` with a clear error message saying that they need to be manually set.
The problem was that accessing those (unset) attributes raised the error -- but, of course, storage needs to access the attributes (in case they exist) to save them.
Fix was to switch some over-fancy stuff based on not *having* the attribute to allow the attribute a default "empty" value (for both `movers` and `choice_probability` in `LockedMoveScheme`). These are attributes that are needed for analysis, …
=> Locked scheme saving

openpathsampling/__init__.py
When working with alpha testers (i.e., Abel) it can be very helpful to check that the installed version of OPS is actually on the git commit that the user thinks it is. `version.py` is only set when the user runs `setup.py`, so we don't want to require that every time. I added a little function to `__init__.py` that gives the git commit hash if the file is in a git repo (it will raise an error otherwise, I think). This is useful for debugging when we can't tell exactly which version of the code the user is using. We might move it to another module, but I wasn't sure which module was appropriate (or if we need a new one).
Anyway, this should be ready to review at any time.
=> Getting the actual git hash for editable installs

openpathsampling/dynamics_engine.py, openpathsampling/tests/test_toy_dynamics.py
Adds a function to `DynamicsEngine` to get multiple frames at once (`generate_n_frames`). This process is only implemented in the forward direction. If the user wants the reverse trajectory, the user can explicitly reverse -- under most such circumstances, it nerateould make more sense to use the existing infrastructure, if that is what is desired. This is intended for the many non-path-sampling examples where we generate a fixed length trajectory from an initial point.
Overriding this default implementation could (with a few other tricks) allow for much faster implementations for fixed-length trajectories on small systems.
=> DynamicsEngine.generate_n_frames

openpathsampling/scripts/openmm.py
This adds a test script that should analyze your openmm installation and give suggestions on how to fix missing platforms.
Can be merged at will. Does not affect any other files.
Some things it checks:
- Check the conda installation and figure out where the dynamic libraries are
- Check if the environment variables set are existing paths and if they contain openmm files.
- Suggest how to set the environment variables appropriately.
=> Add openmm platform testing script

openpathsampling/analysis/single_trajectory_analysis.py, openpathsampling/tests/test_single_trajectory_analysis.py
The version of the single trajectory analysis I previously included calculates the flux out of the state. However, we’re often interested in the flux out of the state and through a given interface. This PR adds the option of adding an interface to the flux calculation. By default, the interface is equal to the state, which gives the same result as before.
This does not change anything that is currently set up, and won’t even make it so that the default `.analyze` function includes the interface. If the user wants to calculate the flux this way, the user has to ask for it explicitly.
One nice trick is that, in implementing this, I recognized that the flux calculation was very similar to a state lifetime calculation. That means they can both use the same code: `get_lifetime_segments`. For …
=> Calculate flux through arbitrary interface with SingleTrajectoryAnalysis

openpathsampling/__init__.py, openpathsampling/analysis/single_trajectory_analysis.py, openpathsampling/tests/test_single_trajectory_analysis.py
Just a few more things to make `SingleTrajectoryAnalysis` easier to use in practice.
Question: Renaming? Neither of the names of classes in `single_trajectory_analysis.py` are very good (`SingleTrajectoryAnalysis` and `TrajectorySegmentContainer`), but I don’t have any better names either. The functionality is definitely useful, though.
=> More cleanup of Single Trajectory Analysis

openpathsampling/analysis/single_trajectory_analysis.py, openpathsampling/ensemble.py, openpathsampling/volume.py
Performance improvements. Five-fold speedup in the DNA analysis I was doing; probably less (but still significant) in our examples.
Timings (in order of my implementations, so these are cumulative improvements) to use `SingleTrajectoryAnalysis.analyze_flux()` on a DNA trajectory of 10k frames. Inexact, since I just ran the test once on my laptop, but when you see a calculation drop from ~5 minutes to ~1 minute, that’s well beyond the margin of error (even for my sample of $N=1$).
* Current `master` branch: `264.98s user 1.95s system 89% cpu 4:56.82 total`
* Rescope debugging: `127.29s user 1.64s system 89% cpu 2:24.61 total`
* Short-circuit volumes: `96.98s user 1.45s system 90% cpu 1:49.07 total`
* Fix split algorithm: `62.83s user 1.35s system 80% cpu 1:19.98 total`
* Fix short-circuit …
=> Major performance improvements: Ensembles, Volumes, Splitting

devtools/ci/install.sh
Right now, miniconda's MD5 doesn't match the value that Travis is seeing. 
I suspect this is a bug on the part of the folks at conda. It fails for me with both [OPS](https://travis-ci.org/choderalab/openpathsampling/builds/119608319) and nightly build on [dynamiq-md](https://travis-ci.org/dynamiq-md/dynamiq_engine/builds/119605522), both failing again after re-running, so I assume this is a bug and not a fluke.
This PR just adds a little more information of "expected" and "found" after an MD5 mismatch in the miniconda setup. Potentially useful debug info that probably should make its way elsewhere.
=> Details of MD5 failues in conda install

openpathsampling/engines/trajectory.py
We currently have the following:
```python
trajectory.not_an_attribute
```
```pytb
---------------------------------------------------------------------------
RuntimeWarning                            Traceback (most recent call last)
<ipython-input-9-4a503b36e4ce> in <module>()
----> 1 traj.not_an_attribute
/Users/dwhs/Dropbox/msm-tis/openpathsampling/engines/trajectory.py in __getattr__(self, item)
195 
196             else:
--> 197                 raise RuntimeWarning('Cannot access attribute "%s" from this type of snapshots')
198 
199         else:
RuntimeWarning: Cannot access attribute "%s" from this type of snapshots
```
Problems with this:
1. Aside from the other issues (parts 2 and 3) this forgot to fill in the `%s`
2. This is confusing to the user, because it is trying to …
=> RuntimeWarning that should be AttributeError in Trajectory

openpathsampling/__init__.py, openpathsampling/analysis/move_scheme.py, openpathsampling/tests/testmovescheme.py
In a number of cases (TPS being a prime example) we frequently want to use only shooting moves. This PR create a `OneWayShootingMoveScheme` object which has the minimum necessary to do shooting.
Note that you can always add other move strategies to this, if you want. For example, if you wanted path reversal as well, you use the `.apply_strategy` function to add that. 
Basically, I’d think of it this way:
* `DefaultScheme` gives a full default for TIS calculations: RETIS, with minus, with path reversal, etc.
* `SRTISScheme` gives a full default for SRTIS: same as `Default`, but with single-replica moves (e.g., ensemble hops instead of replica exchange)
* `MoveScheme` is a completely blank slate that you need to add everything else to
* `OneWayShootingScheme` is added to provide the most …
=> OneWayShootingMoveScheme

openpathsampling/engines/dynamics_engine.py, openpathsampling/pathsimulator.py, openpathsampling/tests/test_shooting_point_analysis.py, openpathsampling/tests/testpathmover.py, openpathsampling/tests/testpathsimulator.py, openpathsampling/tests/testshooting.py
Building off of ideas from the tests I wrote in #454, I’ve written tests for our shooting movers that should catch it if we ever regress on #416 (which relates to these “kinked” trajectories we were seeing when the reversal of the backwards shooting snapshot was done incorrectly.)
@jhprinz fixed the problem a while ago (#429 or, at worst, #445), but I didn’t want to close the issue until we had a more thorough test. This is that test.
Closes #416.
This also includes some fixes to actually allow multiple engines, following on #465. I removed the way engines made themselves default automatically on creation. The place to set the default engine is inside a `PathSimulator`, or directly by using `EngineMover.default_engine`. The implicit defaults were causing problems in tests that involved …
=> Better test for shooting

devtools/conda-recipe/meta.yaml
Most recent MDTraj release ([1.7.0](https://github.com/mdtraj/mdtraj/releases/tag/1.7.0)) should obviate the pin to 1.5.1. Thanks @jchodera for the heads up when https://github.com/mdtraj/mdtraj/pull/1089 got merged.
Resolves #436. (At least, assuming conda knows of that release and that it does fix the problems we had.)
=> Remove pin to mdtraj version 1.5.1

devtools/ci/ipythontests.sh, openpathsampling/ensemble.py, openpathsampling/tests/testensemble.py
This will fix a significant bug in the ensemble code. This boils down to the statement that ensembles should act on trajectories, not on frames. To explain the problem, let's start with some terminology:
***Definition*** *(frame-by-frame ensemble)*: If a trajectory $(x_0, …, x_L)$ is in a *frame-by-frame* ensemble, then all you need is to look at is $x_{L+1}$ to know whether $(x_0, …, x_{L+1})$ is in the ensemble.
For example, consider `AllOutXEnsemble(stateA)`. If we know the value for the previous trajectory, we only need to look at the next frame, without considering the whole trajectory. If all frames $x_i$ with $i<=L$ were outside the state, and frame $x_{L+1}$ is outside the state, then obviously all frames with $i<=L+1$ are outside the state.
However, this is **not** true for …
=> Ensemble cache for frame-by-frame ensembles

openpathsampling/analysis/network.py, openpathsampling/analysis/tis_analysis.py, openpathsampling/tests/testnetwork.py
Right now, if we create a `TPSNetwork` with `from_states_all_to_all`, we get literally *all* the possible transitions, including A->A. Typically, we don’t want the self-transitions to be allowed.
This PR adds an `allow_self_transitions` flag to the creation of `TPSNetwork` and `FixedLengthTPSNetwork`. This flag will default to `False`, in which case there are no A->A transitions.
This makes a rather significant change in the way MSTPS is handled internally: instead of saying that there is only one sequential ensemble to check (leave any state; go to any state), now it is the union of a sequential ensemble for every state (leave that state; go to any other state). This will have some negative effects on speed, especially when building the trajectory backwards. We'll see scaling something …
=> Add `allow_self_transitions` to `TPSNetwork`

openpathsampling/analysis/move_scheme.py
Fixes problem that move schemes included the EmptyMove (used to set initial conditions) when calculating the frequency at which a move was actually used. This gave $N/(N+1)$ for $N$ moves when only one move was possible: so instead of the only move possible being run 100/100 = 100% of the time, it was run 100/101 = 99.01% of the time (gradually getter closer to 100% with more trials, but still, looks like nonsense)
Ready to merge as soon as it passes tests.
=> Fix bug in move scheme frequency calculation

openpathsampling/netcdfplus/netcdfplus.py
This just gives a shortcut to obtain the size of a file associated with a netcdfplus storage. It also gives a property with string output to convert that to a human-readable number in kB, MB, or GB (technically kiB, MiB, or GiB).
This is useful when doing analysis in an ipynb -- it is nice to get an overview of how big the file is before running analysis that might take a while.
Should be ready to merge immediately on passing tests.
=> Add `file_size` and `file_size_str` to netcdfplus

openpathsampling/analysis/move_scheme.py, openpathsampling/pathmover.py
At some point in making the alanine dipeptide examples, I put the storage of the engine in as part of a move scheme. However, this doesn't really make sense -- it needs to be stored with the `EngineMover`, whether it is part of the scheme or not. And it is only passed to the scheme as a convenience function.
This was causing problems for OPSPiggybacker. This PR fixes those problems, and it seems that it also runs (short versions of) the AD TPS examples correctly too. Should be ready for review/merge as soon as it passes tests.
=> Switch engine storage from scheme to mover

README.md, docs/getting_started.rst, docs/index.rst, examples/ipython/README.md
Little changes of `choderalab` to `openpathsampling` org name in READMEs and docs.
I think I got everything. I kept thinking of another place to check every time I added a commit.
This should be immediately ready to merge. There's no new code.
=> Cleanup of docs/READMEs after org change

.coveragerc, openpathsampling/analysis/network.py, openpathsampling/pathsimulator.py, openpathsampling/tests/testpathsimulator.py, openpathsampling/tools.py
When I started writing the section of the paper on the toy model MISTIS and the bootstrapping, I found that a few details that were a bit confusing. I think this may have led to some confusion in the stuff that Abel was doing. To make sure that the behavior in the code matches what I write in the paper, I’m writing tests for the bootstrapping.
This may also lead to some changes in the behavior of the `FullBoostrapping`, and possibly in the `MISTISNetwork`. I think I’ve occasionally seen bad initial conditions in the MISTIS ipynb test, causing annoying failures. I’m hoping that this PR might fix that. At the very least, it will give a nice bump to our test coverage, and ensure that our paper matches our code!
=> Tests and cleanup of bootstrapping

examples/ipython/mistis_flux.ipynb, openpathsampling/__init__.py, openpathsampling/pathsimulator.py, openpathsampling/tests/testpathsimulator.py
This PR adds a simulator class for direct MD calculations of the flux through an interface or of the rate. This is useful because MISTIS requires a separate flux calculation. Although we can calculate the flux from an existing trajectory (see `single_trajectory_analysis` and #435), we often want to calculate the flux without saving every frame (especially with toy models). That is possible with this PR.
=> DirectSimulation for rate and flux

.travis.yml, devtools/ci/after_sucess.sh, devtools/ci/install.sh
Resolves #487.
This will reenable conda upload. Not sure if that is what we want, but I created a new TOKEN and updated the `after_success.py` script to upload a merge on master if it was successful.
=> Enable upload to Anaconda/Omnia after build

examples/ipython/tutorial_path_histogram.ipynb, openpathsampling/__init__.py, openpathsampling/analysis/__init__.py, openpathsampling/analysis/path_histogram.py, openpathsampling/tests/test_path_histogram.py
This PR will implement path density plots. The easiest way to think of path density plots is in terms of what a single path contributes to them: each bin that is traversed by the path adds a count of 1 to the (multidimensional) histogram. This means: (1) it doesn’t matter how long a single path stays in one bin, or how many times it enters that bin; or equivalently (2) important areas of the histogram don’t represent long staying times (stable states), rather, they mean that lots of paths go through there (possible bottlenecks). Path density plots also interpolate (linearly) to include any bins that are skipped between frames.
Historically, path densities have been calculated in a 2D projection. This implementation, based on the `SparseHistogram` code from #504, works in an arbitrary …
=> Path density histogram

openpathsampling/netcdfplus/netcdfplus.py
Really stupid typo of mine. It always reported as "GB" even when it meant "MB", "kB" or even just "B".
7-character fix for a bug @bolhuis caught. This should be ready to merge as soon as it passes.
=> Fix bug in storage string in `netcdfplus`

openpathsampling/engines/dynamics_engine.py, openpathsampling/tests/testdynamicsengine.py
See discussion in #507. This will not solve that issue, but it should make it easier to debug.
A few questions:
* In the event that the re-run works, do we `return result` or raise the `AttributeError`. Currently, I'm raising the error under the assumption that if something went bad, we can't trust the results.
* Do we give a special message for non-property, in-dictionary errors? I'm not entirely sure how to create a test for that scenario; currently it would give the same as an actual does-not-exist.
=> New DynamicsEngine.__getattr__ 

openpathsampling/analysis/move_scheme.py, openpathsampling/tests/testmovescheme.py
Resolves #536.
Debated which should be the default behavior. I think this makes more sense. It also makes it easier to later switch to defaulting to state-swap based things.
=> DefaultScheme does not require MS-outer interface

examples/ipython/mistis_setup.ipynb, examples/ipython/mstis.ipynb, openpathsampling/netcdfplus/dictify.py, openpathsampling/tests/testvolume.py, openpathsampling/volume.py
It adds `simtk.unit` and `simtk.openmm` to the allowed packages and rewrite the 
`CVDefinedVolume` and `PeriodicCVDefinedVolume` that they work also with simtk.unit
Problem was that simtk.unit does not support `%` so I had to rewrite it.
Should pass tests. Ready for review and merge
=> [WIP] Enable simtk.units in CVDefinedVolume

openpathsampling/analysis/tis_analysis.py, openpathsampling/analysis/wham.py, openpathsampling/tests/testwham.py
The problems in #549 were two-fold: both were sampling, but for different reasons. First, sometimes interfaces didn't overlap because no path from the inner interface crossed the outer interface. Second, if 100% of paths in an outer interface went well past the interface boundary, the automatic identification of the interface boundary failed.
Both can be solved by more sampling. The second one, however, could also use the new `InterfaceSet` object to hint what the interface values are.
That's what this code implements. If the interface lambdas are defined in the interface set, then we use that information. If not, we fall back on the old approach.
This should help tests pass some, although the first problem remains.
=> Use interface lambda hinting in WHAM DF cleaning

openpathsampling/engines/features/shared.py, openpathsampling/engines/openmm/engine.py
I changed from trying to report a whole pandas `DataFrame` (a typo in that was the problem) to just reporting the bad atoms.
Also removed the `try: except:` wrappers around `OpenMMEngine._build_current_snapshot`.
See discussion in https://github.com/choderalab/ligand-binding-pathsampling/pull/4
=> Quick fix for NaN reporting problems

openpathsampling/engines/openmm/engine.py
There was a bug (presumeably) by some merge faults so that the openmm_platform_properties were saved with an engine, but not used in the construction of the actual OpenMM Instance.
This will fix this. On my machine now OpenCL does not work with mixed precision. This seems to be the cause of all the `NaN`s.
@jchodera This is an important fix for you, too, if you use OpenCL!!!!
=> Fix OpenMM Precision Bug

devtools/conda-recipe/meta.yaml
We (ab)used the test environement prior to conda-build 2 to also run nose tests, etc. This is not possible anymore so we can remove the packages which should fix windows conda builds.
=> Remove unnecessary packages from test environment

openpathsampling/engines/openmm/engine.py, openpathsampling/engines/openmm/features/__init__.py, openpathsampling/engines/openmm/features/instantaneous_temperature.py, openpathsampling/engines/openmm/snapshot.py, openpathsampling/engines/toy/features/__init__.py, openpathsampling/engines/toy/features/instantaneous_temperature.py, openpathsampling/engines/toy/snapshot.py, openpathsampling/tests/test_openmm_snapshot.py, openpathsampling/tests/test_toy_features.py
Note: these are not intended to be features that are required of every engine. However, they could be very useful.
In particular, I'm pretty sure we want something like `n_degrees_of_freedom`: that shows up in enough other calculations, and will be very much engine dependent. Not having this leads to all sorts of ugliness when I wanted to check instantaneous temperature in the AD TPS example: a lot of code that is OpenMM-specific.
Whether we directly include `instantaneous_temperature` is a little less vital, in my opinion. A competent user can handle that little bit of code for their engine. For now, I've added it for consideration.
=> Snapshot features: `n_degrees_of_freedom` and `instantaneous_temperature`

openpathsampling/netcdfplus/dictify.py
This makes the check for `unsafe` imports optional
=> Remove check for unsafe imports

openpathsampling/high_level/network.py
Something I missed in #610. There was a problem when we re-saved a network that had been saved in the old way. This fixes the problem.
Should be immediately ready for review.
=> Fix resaving bug in TPS storage

openpathsampling/movechange.py, openpathsampling/storage/stores/movechange.py
Simple fix. Resolves #630 .
Problem was for (unknown) reason details were only loaded when caching all if a change had no samples.
=> Fix caching of MoveChanges for changes with no samples

examples/ipynbtests.sh, openpathsampling/movechange.py, openpathsampling/pathmover.py, openpathsampling/storage/stores/movechange.py
We had a lot of old cruft (pre-dating the `MoveChange` object) that was stored as part of various `Details` objects. Following some email discussion with @jhprinz, this PR does the following:
Note that this does not (yet) end the distinction between `MoveDetails` and `SampleDetails`, although now the objects are essentially equivalent (and are just renamed subclasses of `Details`.  @jhprinz, if you think I should change that here, I can easily.
=> Cleanup of `Details` objects

openpathsampling/__init__.py, openpathsampling/analysis/shooting_point_analysis.py, openpathsampling/pathmover.py, openpathsampling/sample.py, openpathsampling/storage/stores/movechange.py, openpathsampling/storage/stores/sample.py, openpathsampling/tests/testopenmmengine.py, openpathsampling/tests/testpathsimulator.py, openpathsampling/visualize.py
This removes the `.details` property from `Sample`. The necessary information is now stored in the `MoveChange`.
=> PathMover update - remove `Sample.details`

openpathsampling/analysis/shooting_point_analysis.py, openpathsampling/pathmover.py
Two very minor fixes:
* #633 left a print statement (used for debugging, I assume?) in `pathmover.py`. Removed that.
* numpy 1.11 will start throwing RuntimeWarnings if `true_divide` has a NaN or divides by zero (I was *using* `true_divide` to get the desired behavior that `NaN/0.0` gives `NaN`!) Conda is still on 1.10, but I've upgraded to 1.11 and see this warning when I run tests locally.
Should be ready for review immediately; just a matter of waiting to pass tests.
=> Fixes for test output

openpathsampling/tests/test_helpers.py
Previously, the default velocities in the `make_1d_trajectory` test helper function was 0.0. This changes that to 1.0. `make_1d_trajectory` is often used in concert with the `CalvinistDynamics` mock engine, where the sign of the velocities tells you which way to step through the pre-determined trajectory. Of course, flipping the velocities doesn't do anything when the velocity is 0.0. Switching the default to 1.0 makes this easier, and doesn't change any of our other tests. (Existing tests that needed this sign flip explicitly named velocities as 1.0 in the input to `make_1d_trajectory`; now that behavior is default.)
=> Switch default velocities in `make_1d_traj` to 1.0

openpathsampling/pathsimulator.py
This should fix a problem that @sroet brought to my attention at the ESDW today. The basic problem is this:
Some path simulators will wrap other path simulators (e.g., for some iterative process). The problem that @sroet was having was that, even if the output of the wrapped simulator was sent to `dev/null`, the `refresh` command was emptying the cell, deleting desired output from the outer simulator.
This adds a new attribute for `PathSimulator`s called `allow_refresh`, which defaults to `True`. When a simulator calls the `refresh_output` command, the `refresh` attribute is set to `self.allow_refresh`. Combining `inner_sim.allow_refresh = False` with `inner_sim.output_stream = os.devnull`, this can completely silence the output behavior of the inner simulator.
@sroet: Could you check out …
=> Method to avoid refreshing ipynb cells from wrapped simulators

openpathsampling/engines/openmm/topology.py
I had problems that in some cases the `mdtraj.Topology.Atom` object does not have a `segment_id` property. In this case the segment_id will be empty. This fixes this, but in the long run we should work on getter a better pickling for the topology.
=> Failsafe for `segment_id` in `to_dict` of mdtraj topology

openpathsampling/pathmover.py
Previously, the `SampleMover` would overwrite the details from engine exceptions, meaning that, e.g., for a shot that hit max length, you couldn't figure out the shooting point. This fixes that.
=> Details on engine exceptions

openpathsampling/engines/openmm/tools.py, openpathsampling/tests/test_mdtraj_support.py
We've talked about adding this before. It's basically an OPS wrapper on MDTraj's `load` method. After MDTraj loads the file, we convert the MDTraj trajectory to an OPS trajectory.
I've locally tested with Gromacs file including a `.gro` for the `top` keyword, and it works. At some point, we'll want to add formal unit tests on that.
(I got tired of every analysis-based example starting with what was basically this little one-line function.)
Would like to put this in 0.9.2, so please review soon.
=> Shortcut: `ops_load_trajectory`

openpathsampling/engines/openmm/features/instantaneous_temperature.py, openpathsampling/tests/test_openmm_snapshot.py
There was a bug in the `instantaneous_temperature` feature for OpenMM engine snapshots. It did not set context with desired snapshot, so the temperature that returns was always the from the last snapshot the engine had generated. Fix, plus regression test, in this PR.
Should be ready for review as soon as it passes tests.
=> Fix OpenMM instantaneous temperature

openpathsampling/__init__.py, openpathsampling/engines/openmm/features/masses.py, openpathsampling/engines/toy/engine.py, openpathsampling/snapshot_modifier.py, openpathsampling/tests/test_snapshot_modifier.py
This PR includes a way to modify the velocities of a snapshot, as described in the early work on 2-way shooting. Note that these techniques can get very complicated if the system includes constraints. To avoid that, this snapshot modifier checks that the number of degrees of freedom is as expected (meaning the engine's snapshots must implement the `n_degrees_of_freedom` snapshot feature, otherwise this raises an error.)
It includes an abstract class `GeneralizedDirectionModifier`, and two concrete subclasses: `VelocityDirectionModifer` (which modifies all velocities) and `SingleAtomVelocityDirectionModifier` (randomly picks a single atom to change its velocity.) Both of these have the ability to restrict the atoms which they change to a subset of the full system (as do all …
=> Velocity Direction Modifiers for 2-way shooting

openpathsampling/pathmover.py, openpathsampling/shooting.py
This fixes a little bug I found when calculating the acceptance probability in 2-way shooting. The issue is this:
In 1-way shooting, when we calculate the acceptance probability (i.e., the length of the trajectory, minus the two endpoints that we don't shoot from) we *always* have a full trajectory. It might be A-to-A instead of A-to-B, but it isn't a half-trajectory.
In 2-way shooting, on the other hand, it could happen that your forward shot lands in state A (in a TPS, A->B ensemble). That means that there's no way for the backward shot to ever give something that satisfies the ensemble, so, intelligently, we quit there and the trial is only the forward partial trajectory.
Of course, this won't be accepted, because it doesn't satisfy the ensemble. However, we were checking the …
=> Fix bug in acceptance probability calculation for 2-way shooting

openpathsampling/analysis/trajectory_transition_analysis.py, openpathsampling/ensemble.py, openpathsampling/tests/test_trajectory_transition_analysis.py
A little bit of improvement to make a direct calculation of the flux (not just the dictionary that is then used to calculate the flux) 
* `analyze_flux` function now works with multiple trajectories as input
* new `flux` function calculates the actual numeric flux (previously, only had the `analyze_flux` method, which returns a dict of the "in" and "out" frames, from which the flux can be calculated)
Also fixes a stupid error in the `analyze` method where I'd flipped "A" and "B". Finally, adds a note for future improvement in `ensemble.py` (unrelated; just something that I noticed could be made faster with a little more algorithmic effort).
=> Updates to flux calc in TrajectoryTransitionAnalysis

openpathsampling/tests/testpathsimulator.py
It was causing problems for tests in the E-CAM modules, for some unknown reason.
=> Remove SkipTest from CommittorSim tests

openpathsampling/__init__.py, openpathsampling/analysis/channel_analysis.py, openpathsampling/tests/test_channel_analysis.py
This adds an analysis object to study how well multiple channels are sampled in path sampling simulations. This could be useful in several contexts: 
* Similar things have been done before to see how well the various final states are sampled in MSTIS. There should be plenty of switching between various final states, which can be seen as different "channels"
* Some TPS simulations can sample different channels (mechanisms) for the same physical transition. This will make it possible to study that as well.
The approach implemented here uses `Ensemble`s (and specifically the `Ensemble.split` function) to characterize channels, as I have previously done in the AD TPS example. The ensembles are the user input. Each path can be characterized as being in one, multiple, or no channels. Then …
=> Channel analysis

openpathsampling/pathsimulator.py, openpathsampling/tests/testpathsimulator.py
`DirectSimulation` keeps its results in the `DirectSimulation` object, using `@property` methods to calculate several quantities from a few simplified internal structures.
Previously, there was no way to save those simplified internal structures. This adds two methods, an `@property` called `results` and a method called `load_results`, which put those internal structures into a `dict` and load from that `dict`.
I chose to do it this way, rather than by modifying the `to_dict`/`from_dict`, because this allows the user to store the simulation object before the results are calculated.
One question: `load_results` is currently a separate method. The other option would be to make it the setter of the `results` property. I'm not sure which makes more sense:
```python
sim = DirectSimulation(...) …
```
=> DirectSimulation result storage

openpathsampling/ensemble.py, openpathsampling/high_level/transition.py
Told you in https://github.com/openpathsampling/openpathsampling/pull/665#issuecomment-280488217 that I'd find a way to fix this. Didn't think I'd do it tonight, though!
Since `Ensemble`s are immutable, their strings should also be immutable. So we calculate the full string once, and then cache it.
The rate matrix speed is even better. Before it was ~40 seconds, now:
At this point, the performance bottlenecks for the rate matrix calculation are the chaindict (I don't think these CVs are cached on disk, so that's more expensive in this case) and within the `collection.Counter` that manages the histogram (there's room to improve the way data is sent to that, but I'll save that for the rewrite of analysis that I'm working on). Loading the data (opening the file as `AnalysisStorage`) is a …
=> Faster minus flux

openpathsampling/high_level/transition.py
Just a few lines of code to provide a significant speed-up for TIS analysis.
Caching previous results of max_lambda, so we don't check it again if we have the same trajectory as before. For the toy model, this nearly doubles the speed (with 20k trajectories).
Before:
After:
Same results; we just get them faster.
=> Faster TIS analysis

openpathsampling/ensemble.py, openpathsampling/pathmover.py, openpathsampling/tests/testensemble.py, openpathsampling/tests/testpathmover.py
This adds a new argument to `Ensemble.__call__`, called `candidate`. If `candidate is True`, then shortcuts can be used to calculate whether the trajectory is in the ensemble. The assumption is that this is a "candidate trajectory," as described in path ensemble theory; i.e., a trajectory that could have been generated by shooting. 
For example, this will allow us to assume that all frames except first and last are not in any state for a (flexible length) TPS ensemble or a TIS ensemble. For ensembles where there is no shortcut to be had, `candidate` just has no effect.
This is the first step toward using the generalized CVs of #662 in analysis (simply need to replace the `TISEnsemble`'s use of max(orderparameter(trajectory)) by a CV that stores that result). That will be a huge …
=> Fast ensemble check

openpathsampling/__init__.py, openpathsampling/pathsimulator.py, openpathsampling/tests/testpathsimulator.py
This refactors some of the committor simulation. It will already be useful for reactive flux, and also for some other things I'm playing with that won't go straight into OPS core.
There are a lot of simulation types that start from a user-provided list of snapshots, and then shoot from those snapshots (often doing something like randomizing the velocities before the dynamics) and run until some ensemble condition is satisfied. This refactors the reusable code from the `CommittorSimulation` into a base class. This was [already suggested by Andreas Singraber](https://gitlab.e-cam2020.eu/Classical-MD_openpathsampling/RF/issues/4), who is developing a reactive flux module for OPS.
=> `ShootFromSnapshotsSimulation`

openpathsampling/ensemble.py, openpathsampling/pathsimulator.py, openpathsampling/tests/test_tools.py, openpathsampling/tools.py
This PR fixes a few minor annoyances with the progress output during a path sampling simulation. In particular, it includes the following:
New output looks something like this:
```
Working on Monte Carlo cycle number 215
Running for 1 minute 44 seconds -  0.91 seconds per step
Estimated time remaining: 5 hours 2.52 minutes
```
The time elapsed is always the full string (`1 day 2 hours 3 minutes 4 seconds`). The time remaining always contains the first two (occupied) "levels" (day, hour, minute, second) with the remainder to 2 decimal places in the last. So (`1 day 2.05 hours`, or as above, `5 hours 2.52 minutes`). I thought this would be the most readable (and it acknowledges that the time elapsed is exact, whereas the time remaining is a rough estimate).
=> Improvements on progress output

openpathsampling/engines/openmm/engine.py
When OpenMM deserializes subclasses of `CustomIntegrator`, it creates a `CustomIntegrator`, meaning that any additional methods defined in the subclass are lost. So, for example, we lose the `getTemperature()` method in `openmmtools.integrator.VVVRIntegrator`.
Fortunately, @andrrizzi came up with a nice solution for that in https://github.com/choderalab/openmmtools/pull/130. So all this does is wrap around his solution, and put it into a function that could be extended for integrators other than `openmmtools` (keeping the code in one place for readability). 
If the restored integrator isn't a subclass of `openmmtools.integrators.ThermostatedIntegrator`, or if, for some reason, the interface can't be restored, then nothing is different. If the interface can be restored, we'll have access …
=> Fix deserialization of `openmmtools.integrator`s

openpathsampling/pathsimulator.py
This fixes a really stupid mistake in `DirectSimulation` that causes problems when you want to run a billion MD steps. (In Python 3, it would have been correct!)
=> range -> xrange in DirectSimulation.run

openpathsampling/high_level/ms_outer_interface.py
The docstring said that `MSOuterTISInterface.make_ensemble` takes a parameter `forbidden`, which is a list of `Volume`s. However, it only worked if `forbidden` was a single `Volume`. This fixes it so that it can take either a single `Volume` or a list of them.
This popped up as a problem when doing a MISTISNetwork with `strict_sampling=True`. The MISTISNetwork code expected MSOuter to do what the docstring said.
=> Fix to make MSOuter.make_ensemble take list of forbidden volumes

examples/toy_model_mistis/toy_mistis_3_analysis.ipynb, openpathsampling/high_level/network.py, openpathsampling/numerics/__init__.py, openpathsampling/numerics/resampling_statistics.py, openpathsampling/tests/test_resampling_statistics.py
Very basic setup for doing some resampling to get error estimates. The main idea is to create an overall framework that takes a function that generates a `pandas.DataFrame` as output (e.g., our `rate_matrix` calculation) and can return the statistics we're interested in. This is all designed for a case where we're using `pandas.DataFrame` as a relatively small table (as it is with our `rate_matrix` and most other analyses where we output a `DataFrame`.)
There are three main parts to this:
1. Selecting sets of samples to use to recalculate (currently, just implementing block resampling; others could be added later)
2. Applying the (user-defined) function to each set of samples, resulting in a set of `pandas.DataFrame`s for each result
3. Getting statistics from the set of …
=> Resampling statistics

.travis.yml, openpathsampling/storage/storage.py
Resolves #643. Super simple, but is more consistent in the naming.
=> Add `storage.tags` shortcut to access `storage.tag`

.travis.yml, openpathsampling/collectivevariable.py, openpathsampling/netcdfplus/base.py, openpathsampling/netcdfplus/dictify.py, openpathsampling/storage/storage.py, openpathsampling/tests/teststorage.py
Addresses #693.
You can now do 
```py
storage = Storage()
storage.simplifier.safemode = True
```
will force the object handling inside the storage to not load any marshalled functions and replace these with None. It will pratically affect all CVs and you need to replace the function manually if you need it.
Caching is not affected.
=> Add possible _safemode_ to object reconstruction

openpathsampling/ensemble.py, openpathsampling/sample.py, openpathsampling/tests/testensemble.py, openpathsampling/tests/testsample.py, openpathsampling/tests/testvolume.py, openpathsampling/volume.py
Addresses #700. This adds `__ne__` to `SampleSet`, `Volume`, and `Ensemble`, together with tests for (concrete class) examples of each. Quick fix that may be overridden by better solutions later; see #701 for discussion.
=> Missing not equal (`__ne__`)

openpathsampling/high_level/move_scheme.py
This fixes a problem with `MoveScheme.move_summary` that @hejung found. I had used `is` in a case where I should have used `==` (to use UUID to check that the mover is the same). Was only a problem in some edge case (not fully identified, since it depended on the scheme) where the scheme was already in memory. For some reason, movers loaded from `storage` were re-instantiated (@jhprinz, any idea how that might have happened)? This meant that the mover in the `change` will be `==` to the one in the scheme, but not `is`.
=> Quick fix for problem with move_summary

openpathsampling/pathsimulator.py, openpathsampling/tests/testpathsimulator.py
This PR involves several small updates and corrections to the `DirectSimulation` object.
=> Updates to direct simulation

docs/api.rst, docs/engines/openmm.rst, docs/examples/index.rst, docs/netcdfplus/stores.rst, docs/storage.rst
We were getting a lot of warnings when building the docs. This fixes most of them (leaving only a couple because the developer documentation is still in progress and missing some files that need to be written).
Most of the warnings had to do with files that had been renamed or relocated, so it was straightforward to fix.
This changes no code -- only docs -- and should be pretty straightforward to review and merge. It's ready as soon as it passes tests.
=> Documentation cleanup

devtools/ci/after_sucess.sh, docs/conf.py
Apparently we've had some deployment issues with our docs for a while. This PR fixes that, and also makes future problems a little easier to troubleshoot.
It used to be that the only way to even build docs (or prep for conda deployment) was if we were both *not* a PR, and on the master branch.
Now we build docs/prep for deployment if we're not a PR, regardless of branch. This still means that in the most common case (PRs), Travis won't take the time to build docs or prep deployment. However, if we want to debug the deployment procedure, we can now create a branch under the `openpathsampling` fork, and that should do all the work up to, but not including, deployment. Ideally, this will be useful for future debugging.
Fixes #711.
=> Docs deployment

docs/index.rst, docs/topics/index.rst, docs/topics/ops_output.rst
In response to some questions we've gotten, I wrote up another "topic" for our documentation. This covers:
* turning off the default progress output (or directing to file)
* reading netCDF *while* running the sim (i.e., that it can be done)
* turning on the logging output
* doing a live visualization to see your simulation in progress
Also, an update to the index page for the release of 0.9.3.
=> Docs update: How to see what your sim does while it runs

openpathsampling/pathsimulator.py, openpathsampling/tests/testpathsimulator.py
Fixes a bug that @bolhuis and I noticed in the `DirectSimulation` flux when there are recrossings of the interface before re-entering the state. Includes a test for this case.
=> Fix bug in DirectSimulation flux

devtools/conda_ops_dev_install.sh
Several projects I'm working on are based on OPS, and I like to test them against the most recent development branch of OPS. In addition, users might want to test their own OPS-based packages against modifications in their own forks of OPS.
In order to make that easier, I've made this little script that does a developer install of OPS (assuming you have `conda` installed). The premise is that, if something (requirements?) changes between conda releases, this script will be updated to make sure that someone has a working version of the most recent version of OPS. Since the repo is downloaded, it also gives them the option to (after the script) add remotes and switch to a branch in a remote.
The idea is that they could `curl` down this script and use it to install during their CI, and we'd …
=> Dev install script

docs/requirements.txt
After #729, there was a package (`packaging`) needed for docs that was missing from the Travis environment. This fixes it.
Going to merge directly when tests pass, since the difference is trivial.
=> Fix error in docs installation

.travis.yml, devtools/ci/install.sh
There seems to be a problem with the stage that installs OPS into a test environment that is causing build failures. I'll see if I can fix it; if not, a version pin on conda or conda-build might do it.
=> Fix problem in conda-build

openpathsampling/analysis/channel_analysis.py, openpathsampling/analysis/tis/core.py, openpathsampling/bias_function.py, openpathsampling/numerics/lookup_function.py, openpathsampling/numerics/wham.py, openpathsampling/pathsimulator.py, openpathsampling/tests/testlookupfunction.py
There are a few warnings that show up in our tests. This PR fixes or silences them.
* `dataframe.set_value` [is deprecated as of pandas 0.21.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0210-deprecations), and this is raising lots of warnings in tests. This PR will replace usage of `.set_value` with the `.at` or `.iat` approaches, as recommended.
* For a long time, numpy has been throwing warnings for divide by zero for some of the WHAM. We actually *want* to generate NaNs there and then ignore them after (the speed of numpy and increased simiplicity of the code make it easier to create the NaNs then filter them). Used to be, numpy didn't warn on this; now it does. In this PR, we silence the numpy warnings for the lines of code that are expected to cause them.
=> Fix warnings that show up in nosetests

docs/developers/advanced_engines.rst, openpathsampling/engines/features/statics.py, openpathsampling/engines/openmm/engine.py, openpathsampling/engines/openmm/tools.py, openpathsampling/engines/trajectory.py, openpathsampling/snapshot_modifier.py, openpathsampling/tests/test_mdtraj_support.py, openpathsampling/tests/test_openmm_snapshot.py
Fixes #710, plus a test to prove it.
In addition, I changed things so that engine developers who want to support conversion to MDTraj just need to add a `mdtraj_topology` attribute/property to their engines (and added relevant docs).
Also made it so that `snapshot_from_testsystem` allows you to select a nonperiodic snapshot. This was useful for testing.
=> snapshot.md box_vectors

openpathsampling/engines/dynamics_engine.py, openpathsampling/tests/testdynamicsengine.py
The `options` for engines has a bunch of type checking, and if the type given isn't the same as the default type, it raises a `ValueError`. I got this error when I tried to replace a `str`-typed default with a `unicode` object. (Note that this will only be a problem in Python 2, since `str` **is** `unicode` in Python 3.)
This PR fixes that problem, and includes a regression test for it as well.
=> Allow unicode for string options in engine option check

devtools/ci/after_sucess.sh, devtools/ci/push-docs-to-s3.py
We were having some problems with the OPS website. For some reason, the S3 upload was incorrectly identifying MIME types, meaning that even though our CSS was being uploaded, it wasn't actually being used as CSS on the website. (This was not an easy thing to debug!)
In this PR, I mainly changed some of the structure of how the `push-docs-to-s3.py` script works. It could do with more cleanup, but this is all to enable quick fixes if something goes wrong with the S3 upload process in the future. The website is already fixed, because I could force the upload from the `docs_deploy` branch, where I did this work.
=> Docs deployment updates

openpathsampling/pathmover.py, openpathsampling/tests/testpathmover.py
This fixes a bug in the `BackwardFirstTwoWayShootingMover` as well as adding several new tests for two-way shooting. The bug was uncovered through the tests, which were implemented because @bolhuis was suspicious of some behavior in two-way shooting in the MISTIS toy example.
The bug was that the wrong shooting point was being used after the backward-first modification (shooting point was from the original trajectory; failed to account for the fact that the new backward segment had affected the shooting point index!)
The new tests include the following:
1. For TPS and TIS, forward-first and backward-first 2-way shooting can abort early in certain circumstances. For example, with forward-first shooting in TPS, if the forward shot lands in state A, there is no reason to do the backward …
=> Fix bug in BackwardFirstTwoWayShooting

docs/api_sections.rst, docs/tis_analysis.rst, docs/topics/absolute_beginners.rst, docs/topics/common_setups.rst, docs/topics/data_objects.rst, docs/topics/index.rst, docs/topics/simulation_setup.rst, openpathsampling/snapshot_modifier.py
The main thing here is a new doc for the "topics" section discussing things that the user has to do before running path sampling (mostly from the standpoint of practical issues). This mainly covers:
* defining states and interfaces
* obtaining initial trajectories
It also includes a couple other cleanups of the docs, most significantly some additional discussion of how to use the `RandomVelocities` snapshot modifier (which really wasn't obvious in OpenMM's unit system without an example).
=> More docs (simulation setup docs)

openpathsampling/engines/openmm/tools.py, openpathsampling/tests/test_mdtraj_support.py
This makes it possible for a user to provide an `np.array` of velocities to `trajectory_from_mdtraj`, and attach those velocities to the results OPS trajectory. Note: since this is part of the interface with MDTraj (as opposed to OpenMM), this does not require explicit units. Instead the implicit units must be nm/ps.
=> Add velocities to trajectory_from_mdtraj

devtools/conda-recipe/meta.yaml, docs/index.rst, openpathsampling/netcdfplus/version.py, setup.py
Release notes:
OpenPathSampling 0.9.4 includes a few new features, several important bug fixes, and a lot of minor improvements. A few highlights include:
* New ability to include velocities when creating an OPS trajectory from and MDTraj trajectory
* New default colors in visualizations (better visibility for the most common type of color blindness)
* Significant updates to the documentation
* Major improvements in Python 3 support
* Critical bug fix in the direct MD flux calculation
* Critical bug fix in two-way shooting
Details on all improvements below. 
* Add velocities as input to `trajectory_from_mdtraj` (#750)
* Tools for converting flux to `pandas` structures (#735)
* Allow unicode for string options in engine option check (#757)
* Fix bug in `BackwardFirstTwoWayShooting` (#752) …
=> Release 0.9.4

.travis.yml, devtools/ci/miniconda_install.sh
Also, renamed `install.sh` to `miniconda_install.sh` to be clearer.
All our tests are failing right now because the `miniconda` MD5 hash is wrong. For whatever reason, when they uploaded 4.4.10, the script linked by `latest` got updated, but all the metadata did not. Relevant lines from https://repo.continuum.io/miniconda/ as I see it now:
```
Miniconda2-4.4.10-Linux-x86_64.sh | 38.0M | 2018-02-20 13:04:23 | dd54b344661560b861f86cc5ccff044b
Miniconda2-4.3.31-Linux-x86_64.sh | 37.5M | 2017-12-19 07:17:31 | da2dd466d26e33a2b1f72fdb853a8ff0
Miniconda2-latest-Linux-x86_64.sh | 37.5M | 2017-12-19 07:17:31 | da2dd466d26e33a2b1f72fdb853a8ff0
```
Problem is, the script linked at `latest` actually *is* `4.4.10`, so we find the MD5 hash for `4.4.10` while we're expecting (based on the table on the …
=> Pin conda version in `miniconda_install`

openpathsampling/visualize.py
Resolves #773 .
Apparently the visualization does not take rejected or _transparent_ marked trajectories in the path tree. This PR changes this to only consider non-transparent ones. Note, that there are different possibilities to mark paths as transparant. The default is rejected, but it can also intermediate (auxiliary) paths which happen inside of movers.
=> omit using rejected paths in correlation visualization

devtools/conda-recipe/meta.yaml, docs/index.rst, openpathsampling/netcdfplus/version.py, setup.py
Doesn't submitting the papers justify a version bump? @jhprinz, I assume you're in favor of another release at this point. If I don't hear from you by noon tomorrow (just over 12 hours from now) I'll assume it's okay to merge this and do a release.
Proposed release notes:
* Only keep existing value stores in attribute_list (#783)
* Omit using rejected paths in correlation visualization (#782)
* Fix problems in notebook tests (#776)
* Fix problem with netCDF not playing nicely with `simtk.unit` (#776)
* Volumes should only be bounded on one side (#772)
* Fix `TISEnsemble` so it allows 0 frames between interface and state B (#772)
* Fix pandas deprecation warning : replace df.as_matrix() with df.values (#781)
* Update minus ensemble implementation (#772)
* Fix …
=> Bump version to 0.9.5

devtools/ci/after_sucess.sh, devtools/ci/push-docs-to-s3.py, docs/data_objects.rst, docs/pathsimulator.rst, docs/topics/data_objects.rst
As of pip 10.0, the `pip.get_installed_distributions()` no longer exists (https://github.com/pypa/pip/issues/5243), so our docs haven't been pushing. This fixes the problem.
It also fixes some problems missing docs after the pathsimulator split #754.
Note that to test this, the docs already had to get pushed (so the openpathsampling.org website already matches this PR).
=> Fix push-docs-to-s3 for pip 10

examples/ipynbtests.sh, examples/tests/test_cv.ipynb, examples/tests/test_netcdfplus.ipynb
We have notebook tests failing in `test_cv.ipynb` and `test_netcdfplus.ipynb`. This seems to be because of something with the numpy string representation (because `ipynbtest` compares string representation here).
This PR will fix it (or find a way around it).
=> Fix notebook tests

openpathsampling/engines/openmm/engine.py
This, combined with pinning to `openmmtools==0.14`, may be a (temporary?) fix for #767.
Update: thanks to @andrrizzi's suggestion in https://github.com/openpathsampling/openpathsampling/issues/767#issuecomment-381629371, this PR now resolves #767 in two ways:
* If the user has `openmmtools 0.14` or older installed, we still work with that (although that will be removed in 2.0, if not before)
* We also work directly with integrators in `0.15`.
=> Attempt to fix for old openmmtools as well as new

openpathsampling/pathmover.py, openpathsampling/tests/test_pathmover.py
`OneWayShootingMover` did not have an `engine` attribute. It could be accessed from the submovers, but this is not very user-friendly.
This PR adds an `engine` property to `OneWayShootingMover` and to `OneWayExtendMover`. It also cleans up formatting to remove some of the unnecessary vertical space.
This should be immediately ready for review/merge.
=> Add engine property to OneWayShooting

openpathsampling/engines/delayedinterrupt.py, openpathsampling/engines/dynamics_engine.py
This was interfering with task distribution using dask.distributed (thanks to Mariusz Uchronski for identifying the problem).
All this does is make the `interrupter` into an attribute of the `Engine`. Defaults to `DelayedInterrupt`; added an `EmptyContext` that can be used to remove the signal catcher with:
```python
from openpathsampling.engines.delayedinterrupt import EmptyContext
engine.interrupter = EmptyContext
```
(Note that the `interrupter` attribute is the *class* itself, not an instance of it. That's important!)
Still WIP while we're experimenting with it.
=> Make DelayedInterrupt context optional

.travis.yml, devtools/ci/miniconda_install.sh
There is some conflict with MSMBuilder (at least, for Py3). This PR will fix that.
I don't see it in my own Py3 installations, where I use the `conda-forge` channel, so I'm hoping that adding the `conda-forge` to our channels will fix the problem. 
In any case, `conda-forge` is now the recommended channel for Omnia projects, unless there's a specific reason to use the `omnia` channel, so we might as well search it first.
=> Add conda-forge to channels

openpathsampling/netcdfplus/base.py, openpathsampling/tests/test_interface_set.py, openpathsampling/tests/test_network.py, openpathsampling/tests/test_pathsimulator.py, openpathsampling/tests/test_shooting_point_analysis.py, openpathsampling/tests/test_storage.py
I've switched to using Python 3.7 as my primary development environment -- a big jump from 2.7! This PR fixes a few warnings I was getting when running the tests in 3.7.
1. `inspect.getargspec` is deprecated and will be removed in 3.8. Using a try/except to prefer `inspect.getfullargspec` when available (Py3k) and fall back to `inspect.getargspec` when not. (This only occurs once, in `netcdfplus/base.py`.)
2. We were getting a weird error (multiple times) at the end of pytest:
Error in sys.excepthook:
Original exception was:
This didn't actually cause the tests to fail, but certainly looked bad. It turns out that this was happening in tests that had opened a file for writing, but not closed the file after. Closing the file fixes. Figured it out pretty quickly thanks to …
=> Fix warnings for Python 3.7

.travis.yml, devtools/conda-recipe/meta.yaml, examples/ipynbtests.sh, examples/toy_model_mistis/toy_mistis_1_setup_run.ipynb, examples/toy_model_mistis/toy_mistis_3_analysis.ipynb, openpathsampling/analysis/path_histogram.py
This refactors a few parts of the path histogram code. Technically, this is an API break: there were methods that *should* have been private, but were part of the public API (methods related to the interpolation). This PR refactors so that there is a separate class `VoxelInterpolator`, with subclasses `NoInterpolation` and `SubdivideInterpolation`. Note that this does not affect the tests at all; all the tested behavior remains the same.
This will make it much easier to implement alternative interpolation algorithms (which may be much faster than what we have now).
=> Refactor path histograms

docs/api_sections.rst, docs/numerics.rst, openpathsampling/numerics/resampling_statistics.py, openpathsampling/numerics/wham.py
This makes it possible to access the `lnZ` from a WHAM calculation after the combined histogram has been made. This is useful for things like the reweighted path ensemble.
It also adds API documentation for the `numerics` subpackage. (Docstrings were there, but they didn't have a place in a toctree!)
=> Minor updates to WHAM, add numerics docs

devtools/conda_ops_dev_install.sh, docs/install.rst
The correct way to install omnia packages is now (and has been for a while):
```
conda install -c conda-forge -c omnia $PACKAGE_NAME
```
Based on a report from @bolhuis, it sounds like missing `conda-forge` can cause a segfault. This PR updates the installation docs to provide the correct command.
This should be immediately ready for review, since it is a very simple PR. I'll merge it tomorrow (Tuesday 23 April) if there are no objects before then.
=> Update installation docs to include conda-forge

devtools/ci/miniconda_install.sh
Our Py 3.5 builds are failing on Travis because conda is taking too long to solve the environment. Granted, we should be moving away from 3.5, but conda performance is an issue in general. It just isn't quite bad enough to cause Travis failures for other Python versions.
To make this faster, I'll work through some of the steps described here: https://www.anaconda.com/understanding-and-improving-condas-performance/
=> Improve conda performance

openpathsampling/engines/openmm/tools.py
As discussed in #832, `snapshot_from_pdb` should use the same code path (for creating velocities; setting box vectors) as related functions. Namely, the main functionality should be in `trajectory_from_mdtraj`. This PR makes it so that it uses `ops_load_trajectory`, which in turn uses `trajectory_from_mdtraj`.
In the future, I think we should deprecate the `simple_topology` option. The topology should only be made once, which would mean that the performance concern is not a worry.
=> snapshot_from_pdb should use same code path as other functions

openpathsampling/engines/openmm/tools.py
I was working on a system where I read in a really long trajectory (10^5 frames) with MDTraj, and then convert that to an OPS trajectory using `paths.engines.openmm.tools.trajectory_from_mdtraj`. It was agonizingly slow, so I looked into the code.
In our code, we obtained the box vectors from the MDTraj trajectory inside the loop over frames. However, MDTraj's `unitcell_vectors` is a `@property`. This means that, for every frame, we were recalculating *all* the unitcell vectors, and then selecting the one relevant to the frame we wanted, leading to quadratic scaling.
In this PR, I fix that by moving the box vector calculation outside of the loop over frames, so that it is only done once. Still passes all tests, and was *much* faster for my use case!
This should be immediately ready for …
=> Improve performance on trajectory_from_mdtraj

devtools/conda_ops_dev_install.sh
This is a tiny follow-up to #824. Apparently the way I called `cut` doesn't work with all versions of `cut`.  Old method of `cut -d "." -f1 -f2` doesn't work everywhere, instead use `cut -d "." -f1,2`.
Since this is tiny, I will merge it as soon as tests pass.
=> Dev install: More widely-compatible `cut` call

devtools/ci/after_sucess.sh, devtools/install_recipe_requirements.py, docs/acknowledgments.rst, docs/api_sections.rst, docs/index.rst, docs/install.rst
Fixes #846, plus a few other issues (in particular, I noticed that our docs were building on all Python versions, not only the deploy version — not a problem,  but a waste of time on Travis.)
=> Update docs; remove need for conda (library) in dev install

examples/ipynbtests.sh, examples/tests/test_pyemma.ipynb
In #847, I started seeing some flaky test behavior in the `test_pyemma.ipynb` notebook. It would often fail on Py 3.6 and/or 3.7. It looks like it might have something to do with storage (it fails after reloading CVs from storage).
I can't reproduce it locally, so this PR first an attempt to see if I can diagnose the problem. I've turned on verbose output for that notebook.
=> Flaky test_pyemma.ipynb tests

openpathsampling/engines/features/shared.py, openpathsampling/engines/openmm/engine.py, openpathsampling/tests/test_shared.py
Resolves #832. Currently, netcdfplus creates a storage space for box vectors as `n_spatial` x `n_spatial` arrays. If you create a nonperiodic system, the box vectors are `None`. When trying to save the snapshot, it raises an error, since `None` can't be reshaped into the correct size array.
Here, I modify the `StaticContainerStore` such that it will convert box vectors `None` to an array of all zeros for storage, and when loading, will convert a box vector array of all zeros to `None`.
=> Fix problems with storage for nonperiodic systems

openpathsampling/numerics/histogram.py, openpathsampling/tests/test_histogram.py
When trying to do TIS analysis I ran into a bug where the `min_bin` location was either in `bin_space` or in `cv_space` which led to a mismatch between bins and counters.
This became apparent by `reverse_cumulative` returning `0` instead of a `LookUpFunction`. 
The mismatch has been fixed and `(reverse_)cumulative` now gives a `UserWarning` if the total sum is `0` and now returns a LookUpFunction with only zeros.
=> Fix bug with left_bin_edge in histogram

devtools/optional_packages.txt, openpathsampling/collectivevariable.py, openpathsampling/deprecations.py
MSMBuilder is not being maintained. Its `conda-forge` build pins numpy to 1.12. OpenMM 7.4 requires numpy>=1.14, (although this requirement is implicit, not explicit, so we end up with test failures when we try to run OpenMM with an old version of numpy, see https://github.com/openmm/openmm/issues/2385).
I think the solution on our end is to deprecate the integration with MSMBuilder (`MSMBFeaturizerCV`). In principle, we can keep it around, but we can't test it in the same environment as the newest OpenMM.
I'm marking it as deprecated and to be removed in 2.0, with the thoughts that:
1. I don't think anyone was using this functionality in OPS.
2. It's more important to keep up to date with OpenMM.
3. If someone picks up MSMBuilder maintenance, we can always "undeprecate."
=> Deprecate MSMBuilder

openpathsampling/collectivevariable.py
This morning, running `py.test` with python `3.7`. Spat out these `DeprecationWarning`s:
```
openpathsampling/collectivevariable.py:205
/home/sander/github_files/openpathsampling/openpathsampling/collectivevariable.py:205: DeprecationWarning: invalid escape sequence \*
"""
openpathsampling/collectivevariable.py:396
/home/sander/github_files/openpathsampling/openpathsampling/collectivevariable.py:396: DeprecationWarning: invalid escape sequence \*
"""
openpathsampling/collectivevariable.py:461
/home/sander/github_files/openpathsampling/openpathsampling/collectivevariable.py:461: DeprecationWarning: invalid escape sequence \*
"""
openpathsampling/collectivevariable.py:627
/home/sander/github_files/openpathsampling/openpathsampling/collectivevariable.py:627: DeprecationWarning: invalid …
```
=> fix DeprecationWarning about invalid escape characters

docs/openpathsampling.bib
This just makes it so that the OPS bibtex files give correct capitalization for titles. Will leave it up for 24 hours in case someone has comments, but there's really nothing controversial in here.
=> [docs] Protect caps in openpathsampling.bib

devtools/ci/miniconda_install.sh
Tests are failing because of https://github.com/conda/conda/issues/9337. Will merge this immediately once I get tests passing. Only affects CI.
=> Workaround for conda trying to remove setuptools on update

openpathsampling/engines/openmm/features/__init__.py
Something seems to have changed between the last test run of #867 and when I merged it, and the minimal install is now giving an error. Fixing that here.
=> Fix minimal install

openpathsampling/pathmover.py, openpathsampling/tests/test_pathmover.py
Currently, the `MinusMove` saves no details. Theoretically, that's fine, because everything is accessible in its subchanges. But practically speaking, asking users to spelunk through the subchanges is a terrible user experience. This brings a couple of things into a `Details` object saved by the `MinusMove` in its `change`:
* `segment_swap_samples` : The samples used in the initial replica exchange between the innermost ensemble and the "segment" of the minus ensemble.
* `extension_trajectory`: The trial trajectory made by the extension phase of the minus move.
Idea comes from #873.
=> Add information to MinusMove change.details

.travis.yml, devtools/ci/pytests.sh, devtools/testing_requirements.txt
This should fix some occasional problems with coveralls not combining coverage correctly. I haven't noticed the problem in OPS as much as in other projects, but I expect we'd have the same issues.
=> Fix coveralls parallel build issues

openpathsampling/engines/toy/pes.py
During a side project that I was playing with, I noticed that the toy engine PES terms don't have useful `__repr__`s. This just fixes up a few of them; enough to make it easier to do what I was playing with. Someday someone should go through and make good reprs for all OPS objects.
I'll leave this up for 24 hours (until at least Saturday night) for review. I can't imagine there's much to discuss, thought.
=> Some toy engine reprs

openpathsampling/engines/toy/pes.py
Since the update to the docstrings of the toy pes I got a couple of: `openpathsampling/openpathsampling/engines/toy/pes.py:198: DeprecationWarning: invalid escape sequence \s
"""` on python `3.6`
This MR fixes that issue(by making them raw strings).
It also makes sure the math is actually compiled through latex for the website, and some pep fixes.
=> fix docstring Deprecation warning

openpathsampling/engines/features/base.py, openpathsampling/engines/openmm/features/__init__.py, openpathsampling/engines/openmm/features/traj_quantities.py, openpathsampling/engines/openmm/snapshot.py, openpathsampling/engines/trajectory.py, openpathsampling/tests/test_openmm_snapshot.py
This simplifies `Trajectory.__getattr__` and may fix #878.
It adds a small restriction on snapshot "features" -- if you have a snapshot feature named `foo`, and if you create a function-type snapshot feature called `trajectory_foo`, then `trajectory_foo` must be a function that takes a trajectory and returns the values for `foo`. (I don't think this is going to cause any problems for anyone.)
I'm using those trajectory function features for the following: With the OpenMM engine, a trajectory returns a `simtk.unit.Quantity` wrapping a numpy array of the results of some snapshot feature, as opposed to making a list/numpy array containing multiple `Quantity` objects. I've now moved the code that supports this behavior into the OpenMM engine (as trajectory function features specific to it), …
=> Simplify Trajectory.__getattr__

.travis.yml, devtools/conda-recipe/meta.yaml, openpathsampling/engines/openmm/topology.py, openpathsampling/netcdfplus/netcdfplus.py, openpathsampling/netcdfplus/version.py, openpathsampling/tests/test_attribute.py, openpathsampling/tests/test_collectivevariable.py, openpathsampling/tests/test_mdtraj_support.py, openpathsampling/tests/test_openmm_tools.py, openpathsampling/tests/test_storage.py, setup.cfg
The marquee feature in OPS 1.1 is the addition of GROMACS support. That also introduces the external engine framework, which can be used by other MD engines.
Another important change is that OPS is now pip-installable and can be installed through conda's `conda-forge` channel (starting with 1.1, new versions of OPS will *not* be in the `omnia` channel). Also note that many tools that previously were bundled with OPS now are not. In particular, if you want to use any of the following packages, you must install them separately:
* OpenMM
* OpenMMTools
* PyEMMA
* MSMBuilder
* Jupyter
They're all just a `conda install` away, and as soon as they're in your environment, OPS will interface with them as before.
Deprecations: CVs based on MSMBuilder featurizers are deprecated. MSMBuilder can no …
=> Release 1.1.0

docs/api_sections.rst, docs/interface_set.rst
This adds a place in the API docs for interface sets.
This PR only touches the docs, and can't be controversial, so I'll merge as soon as it passes tests. (If anyone wants to improve wording/fix typos, that can be done in a separate PR).
=> Add interface_set to API docs

openpathsampling/progress.py, openpathsampling/tests/test_progress.py
One of the annoying things when working with OPS is that sometimes analysis takes a while, and there's no indicator of how long it will take. This PR starts to add optional progress indicators (using `tqdm`) to our analysis tools, by creating a mix-in class that allows users to set the `progress` attribute. Classes that use the mix-in should not define either a `progress` attribute or a `_progress` attribute.
The code here doesn't require tqdm, but uses it if it is present on the user's system (which, I think, it almost always is).
Really, these are adapter classes and we could interface with other progress meters as well, not just tqdm. Also, although I'm mainly focused on analysis, there's no reason (in principle) that this couldn't be used for simulations as well.
Eventually we'll move …
=> Add progress meter adapter classes

openpathsampling/pathsimulators/path_sampling.py, openpathsampling/tests/test_pathsimulator.py
This adds a function to the `PathSampling` path simulator to tell it to run until all trajectories in the initial sample set are decorrelated (in the one-way shooting sense of "not having any configurations in common with the original trajectories.")
This definition of decorrelation is an absolute bare minimum requirement for equilibration, and so you could imagine equilibration strategies such as "run twice as long as it takes to get a decorrelated trajectory" or "run as long as it takes to get a decorrelated trajectory, plus N additional steps." This function will facilitate that.
=> Add PathSampling.run_until_decorrelated

openpathsampling/pathsimulators/path_sampling.py, openpathsampling/tests/test_pathsimulator.py
PR #884 added a `run_until_decorrelated` function to the `PathSampling` path simulator. However, that function didn't use the decorrelated trajectory check that accounts for time reversibility (i.e., it allowed a path reversal to count as decorrelating a trajectory). Since this is intended for equilibration, that doesn't make sense: it should require that the frame be completely replaced (since initial frames may come from nonphysical trajectories).
This fixes that by default, providing `run_until_decorrelated` with a `time_reversal` argument like that in `Trajectory.is_decorrelated`. In this case, that argument default to `True`.
This also updates so that the output for the final step makes it clear that all trajectories have decorrelated, and switches the testing to use a TIS network …
=> `run_until_decorrelated` should account for time reversibility

openpathsampling/high_level/network.py
Pandas 1.0 has been released! And long-deprecated the `.set_value` method for setting dataframe values has been removed. This fixes the places where we were using that (in TIS rate matrix calculations).
=> Fix pandas API change: set_value -> at

openpathsampling/snapshot_modifier.py, openpathsampling/tests/test_snapshot_modifier.py
This will make it so that the preferred way to randomize velocities is in the engine. If the engine knows how to randomize, then we prefer to have the engine create the random snapshot. If not, we fall back on the approaches we have previously implemented (which require that the engine has implemented `apply_constraints`, which should apply the velocity constraints as well; e.g., RATTLE).
To use this, engines should define a method `randomize_velocities(snapshots, beta=None, subset_mask=None)` which returns a snapshot with the randomized and constrained velocities.
This is the first step toward #889.
=> Refactor RandomVelocity so engine can do the work

openpathsampling/numerics/wham.py, openpathsampling/tests/test_resampling_statistics.py, openpathsampling/tests/test_tis_analysis.py
This started with the warnings:
```python
DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
Z_new = pd.Series(index=hists)
```
and 
```python
FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
```
Which led to the same warnings as #881 after touching the files.
This also fixes some pep8 complaints and a small logic error in `TestTotalCrossingProbability.test_calculate()` where the result was checked for AB twice instead of both `AB` and `BA`
=> Fix pandas Deprepaction and Future Warnings

openpathsampling/ensembles/visit_all_states.py, openpathsampling/tests/test_visit_all_states.py
This is a tiny fix. Missing a newline prevented refresh from working correctly in a terminal (apparently it wasn't a problem in notebooks, where I had used it before).
Literally adds 2 characters. I'll merge as soon as tests pass; no need to wait for review.
=> Fix missing newline in the VisitAllStatesEnsemble

openpathsampling/analysis/path_histogram.py, openpathsampling/high_level/move_scheme.py, openpathsampling/tests/test_movescheme.py, openpathsampling/tests/test_path_histogram.py
This adds progress indicators (i.e., tqdm support; introduced in #882) for path density/path histogram objects, as well as for the `move_summary`. With tqdm installed, you automatically get progress bars for these analyses.
=> Progress indicators for path density; move summary

docs/engines/gromacs.rst, docs/examples/miscellaneous/gromacs.rst, docs/videos.rst, openpathsampling/analysis/channel_analysis.py, openpathsampling/engines/dynamics_engine.py, openpathsampling/engines/external_snapshots/snapshot.py, openpathsampling/engines/gromacs/engine.py, openpathsampling/engines/snapshot.py, openpathsampling/volume.py
We've had the Gromacs engine working in OPS since version 1.1, and the docstrings were in place and there was an example in the `examples/` directory. However, none of this stuff had made it to the website. This PR puts it there.
While I'm at it, I'm going to try to clean up a few complaints that I see coming from sphinx.
=> Add GromacsEngine to docs

openpathsampling/storage/storage.py
See also the corresponding Issue #779 .
(Maintainer edit: closes #779)
=> fixed caching_mode='unlimited'

openpathsampling/netcdfplus/netcdfplus.py
=> storage.filename is now an absolute path and a read-only property

openpathsampling/analysis/shooting_point_analysis.py, openpathsampling/tests/test_shooting_point_analysis.py
closes #722
I reimplemented the TransformedDict.__iter__() method and updated the corresponding test.
Now self.values(), self.keys() and self.items() work consistently and return counter, snapshots and tuples of them respectively.
=> Fix Shooting Point Analysis

openpathsampling/engines/external_engine.py, openpathsampling/pathsimulators/direct_md.py
From an email report from a user:
> I tried to follow this example: 
>
> http://openpathsampling.org/latest/examples/mistis.html#toy-model-mistis
>
> to set up openpathsampling.DirectSimulation for my flux_pairs, but got this error: 
> 
> ```python
> AttributeError: 'GromacsEngine' has no attribute 'n_frames_since_start', nor does its options dictionary
> ```
Two problems, both solved in this PR:
1. `ExternalEngine.n_frames_since_start` is only set in its `.start()` method. It should be set (to `None`) in `__init__`.
2. `DirectSimulation` is not using the `.start()` and `.stop()` methods. This didn't matter for OpenMM/toy engine, but does for external engines like Gromacs.
NOTE: I would not recommend using `DirectSimulation` on external engines. `DirectSimulation` is mainly useful to get …
=> DirectSimulation should use engine.start/.stop

openpathsampling/engines/external_snapshots/snapshot.py, openpathsampling/tests/test_external_snapshots.py
`ExternalMDSnapshot` was moved to a different file, and didn't get all its module-level names redefined. Bug uncovered by @jasperdenduijf in #907.
~~Right now, this still requires tests~~ (tests added!). We're missing coverage on the lines that caused that part of the issue in #907, so we should have tests covering those lines.
=> Fix missing names in ExternalMDSnapshot

openpathsampling/netcdfplus/dictify.py
Since `ujson` version `3.0.0` tests based on openpathsampling saving start failing.
`ujson.dump()` now has default keyword `reject_bytes=True` which leads to issues for dumping CV's (which contain bytestrings).
I had to do some import `if` statements as well as this keyword is not valid for `ujson` = `2.x`  (And I supposed you still wanted to support that version.)
=> Set reject_bytes=False for ujson >= 3

openpathsampling/netcdfplus/dictify.py
This is the same that @sroet did in #917. I only added the `ujson_kwargs` to another call to `ujson.dumps`.
=> support ujson v3 (part 2)

openpathsampling/high_level/transition.py
This came up on experimental storage, but should also be a bug on `master`.
If you load your `network` from one `Storage object`, but your `steps` from another (loading the same file), you might end up with 2 different `instances` of the same `Ensemble`. 
The `is` evaluation is then too strict to handle this. 
I opted to convert this to an `uuid == uuid`
I am having trouble setting up a test case for this, so if you have any pointers for that @dwhswenson, please let me know.
I would envision something like this should fail on master (but I don't have any workable `.nc` files at the moment, and couldn't quickly spot one in the test directory)
```python
import openpathsampling as paths
s1 = paths.Storage("test.nc", 'r')
s2 = paths.Storage("test.nc", 'r')
network = s1.networks[0] …
```
=> use uuid instead of 'is' for selecting ensembles in rate calculation

examples/toy_model_mstis/toy_mstis_3_analysis.ipynb
Apparently pandas no longer allowed tuples as indices? At least, that fixed it locally.
=> Fix toy_mstis_3 for change in pandas

devtools/testing_requirements.txt, docs/requirements.txt, pinned, setup.cfg
*  Pinning ujson < 2 resolves #922. (@hejung -- this is correct, right?) Long term solution is that the new storage I'm working on doesn't require ujson.
*  Pinning nbconvert < 6 fixes a [problem in current builds of docs](https://travis-ci.org/github/openpathsampling/openpathsampling/jobs/727635606#L4066-L4075). Something fails and then hangs in our custom notebook conversion sphinx plugin (written by @jhprinz and no longer maintained). Long term solution is to move to nbsphinx.
* Removed pin on pytest 5.3.4. Still shouldn't use that specific version, but pytest is up to 6.0 now, so I see no need to keep a pin to avoid a [single specific regression](https://github.com/openpathsampling/openpathsampling/pull/893#issuecomment-576643126).
=> Pin ujson<2; nbconvert<6

docs/cli.rst, docs/index.rst
A while ago, I wrote up a [command line interface](https://github.com/openpathsampling/openpathsampling-cli) for running simulations with OPS. I finally finished up its unit tests, so I figure it's worth putting some mention in the core OPS docs. The CLI has [it's own development docs site](https://openpathsampling-cli.readthedocs.io/en/latest/) as well.
Writing custom CLI commands is unbelievably easy, and the code uses a plugin architecture, so you can have your own commands that do things your way without needing to maintain a separate fork of the CLI or having to merge things into it.
This is a docs-only PR, so I'll just leave it up for 24 hours.
=> Add CLI docs to core

openpathsampling/netcdfplus/stores/attribute.py
In netcdfplus, storing CVs (`PseudoAttribute`s) requires a template object to be already stored. Originally we only had CVs that mapped snapshots to computed values, but eventually @jhprinz added the ability to use other objects (like trajectories) as inputs. However, the error message didn't get updated, and it is very confusing to get an error message saying to save a snapshot when you already have a snapshot saved (but need to save a trajectory).
This whole issue will be irrelevant with SimStore, but might as well fix the confusing error message.
=> Improve CV storage error message about missing templates

openpathsampling/sample.py
Going from 5570cd31 to ace9d7e7 and running the tests surfaced another 
```
/home/sroet/github_files/openpathsampling/openpathsampling/sample.py:10: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import Counter, Mapping
```
This solves that one (`Counter` still has to be imported from base `collections`)
=> Fix collections.abc DeprecationWarning in sample.py

openpathsampling/engines/openmm/features/instantaneous_temperature.py, openpathsampling/tests/test_openmm_snapshot.py
Currently, for an OpenMM snapshot, `snapshot.instantaneous_temperature` will raise `Exception: Particle positions have not been set` if no snapshot has been loaded into the engine (e.g., via setting `engine.current_snapshot`). Analysis will frequently not set that, and so it should be possible to calculate the instantaneous temperature without having done that.
This updates the tests for this and other OpenMM engine-based features to ensure that they work if the engine hasn't set its snapshot yet.
=> OpenMM instantaneous temp should work if positions not set

openpathsampling/experimental/simstore/custom_json.py, openpathsampling/experimental/simstore/sql_backend.py, openpathsampling/experimental/simstore/storable_functions.py, openpathsampling/experimental/simstore/storage.py, openpathsampling/experimental/simstore/tags_table.py, openpathsampling/experimental/simstore/test_sql_backend.py, openpathsampling/experimental/simstore/test_tags_table.py, openpathsampling/experimental/simstore/wrapper.py, openpathsampling/experimental/storage/ops_storage.py
This PR adds a `tags` table to SimStore storages. As with `netcdfplus`, the `tags` table can be used to store arbitrary data. Any JSON-serializable object, or any object with a SimStore UUID, can be saved as a named tag.
This PR also includes some additional cleanup after #929 and miscellaneous support so that SimStore can be used in the OPS CLI (see also https://github.com/openpathsampling/openpathsampling-cli/pull/29).
=> SimStore: Tags

openpathsampling/experimental/simstore/memory_backend.py, openpathsampling/experimental/simstore/sql_backend.py, openpathsampling/experimental/simstore/storage.py, openpathsampling/experimental/simstore/test_sql_backend.py, openpathsampling/experimental/simstore/tools.py
Pretty much what the title says. Before, there was an error if you opened a new file as append, because it tried to read the non-existent schema from the file.
Also cleans up some deprecations from importing ABCs from `collections`, not `collections.abc` (SimStore is Python 3+.)
=> Fix bug in SimStore when appending to non-existent files

openpathsampling/engines/features/numpydoctools.py
This PR resolves #943 by fixing a SyntaxWarning that affects Python >=3.8. Also affects #864, #871.
=> Fix SyntaxWarning (resolves #943).

openpathsampling/engines/gromacs/engine.py, openpathsampling/tests/test_gromacs_engine.py
Closes #942. As proposed there I slightly modified the test to reset the counter via its own `reset()` method instead of via the engines `set_filenames()` method. 
Engine works and test pass with and without the counter reset in `set_filenames()`, so it is now a matter of preference if we want to have that reset in `set_filenames()`. I left it in for now, was not sure what your preference is here.
=> fix for filname counter of gromacs engine (fixes #942)

openpathsampling/experimental/simstore/sql_backend.py, openpathsampling/experimental/simstore/storable_functions.py, openpathsampling/experimental/simstore/storage.py, openpathsampling/experimental/simstore/test_storable_function.py, openpathsampling/experimental/simstore/test_type_ident.py, openpathsampling/experimental/simstore/type_ident.py, openpathsampling/experimental/storage/collective_variables.py, openpathsampling/experimental/storage/test_collective_variables.py, openpathsampling/high_level/interface_set.py
SimStore storable functions (CVs) no longer need to have result type provided. Instead, is it identified when the results are first saved. This changes some of the SimStore API, which is only relevant to anyone already using SimStore-based CVs (which are not only experimental, but not even in a release yet.)
=> SimStore: Type identification

openpathsampling/engines/features/kinetics.py, openpathsampling/engines/features/shared.py, openpathsampling/engines/features/statics.py, openpathsampling/engines/openmm/snapshot.py, openpathsampling/engines/openmm/tools.py, openpathsampling/experimental/simstore/attribute_handlers.py, openpathsampling/experimental/simstore/class_info.py, openpathsampling/experimental/simstore/class_lookup.py, openpathsampling/experimental/simstore/custom_json.py, openpathsampling/experimental/simstore/proxy.py, openpathsampling/experimental/simstore/serialization.py, openpathsampling/experimental/simstore/serialization_helpers.py, openpathsampling/experimental/simstore/sql_backend.py, openpathsampling/experimental/simstore/storable_functions.py, openpathsampling/experimental/simstore/storage.py, openpathsampling/experimental/simstore/test_attribute_handlers.py, openpathsampling/experimental/simstore/test_class_info.py, openpathsampling/experimental/simstore/test_serialization.py, openpathsampling/experimental/simstore/test_storable_function.py, openpathsampling/experimental/simstore/test_tags_table.py, openpathsampling/experimental/simstore/uuids.py, openpathsampling/experimental/storage/monkey_patches.py, openpathsampling/experimental/storage/ops_storage.py, openpathsampling/experimental/storage/simtk_unit.py, openpathsampling/experimental/storage/snapshots.py, openpathsampling/experimental/storage/test_snapshot_integrations.py, openpathsampling/high_level/move_scheme.py
This will make it possible to store OpenMM snapshots in SimStore.
Note:  this changes OpenMM snapshots so that the `KineticContainer` and `StaticContainer` objects, which are wrappers around the velocities and coordinates/box vectors, respectively, now also carry information about the engine of their associated snapshot. This *should* be fully backward compatible with the old storage. I've done some minor testing of that, but it would be nice if someone with older files (maybe @sroet, @arjunwadhawan, or @hejung?) could double-check that they can open/analyze older netcdfplus files when they check out this branch.
This also involves significant refactoring under the hood of SimStore, making it more flexible with regards to adding user-defined types.
I'm going to add some unit tests and …
=> SimStore: Support for OpenMM snapshots

openpathsampling/experimental/storage/ops_storage.py
Finally settling internally on the API: You can now set up an OPS storage with:
```python
storage = Storage(filename, mode)
```
No more of this `from_backend` stuff!
=> SimStore: Simplify OPS Storage constructor

openpathsampling/analysis/shooting_point_analysis.py, openpathsampling/tests/test_network.py, openpathsampling/tests/test_pathsimulator.py, openpathsampling/tests/test_shooting_point_analysis.py
Since `numpy=1.19` `array.tostring()` is deprecated, and should be replaced with `.tobytes()` (present in `numpy >=1.9`), this PR does that for OPS.
The leftover `>40000` warnings in the test suite come from `NetCDF4` which has been fixed in [this PR](https://github.com/Unidata/netcdf4-python/pull/1024) (I tested this locally and it passes without these DerpecationWarnings).
Also cleaned some `pep8` complaints on the files I touched.
=> fix numpy 1.19 DeprecationWarning: tostring() 

openpathsampling/tests/test_features.py
If `OpenMM` is installed, but `OpenMMTools` isn't,  the test `TestFeatures.test_copy_with_replacement_openmm`
fails with:
```python
def test_copy_with_replacement_openmm(self):
if not paths.integration_tools.HAS_OPENMM:
raise SkipTest
>       sys = omt.testsystems.AlanineDipeptideVacuum()
E       AttributeError: 'NoneType' object has no attribute 'testsystems'
```
This is due to the code-block at the start of that file:
```
try:                                                                            
import openmmtools as omt                                                   
except ImportError:                                                             
omt = None   
```
This alters the test such that it is also skipped if `omt is None`
Also cleans up some `pep8` complains in that …
=> fix omt is None error in test suite

openpathsampling/__init__.py, openpathsampling/collectivevariable.py, openpathsampling/deprecations.py, openpathsampling/engines/openmm/engine.py, openpathsampling/high_level/interface_set.py, openpathsampling/high_level/network.py, openpathsampling/pathmover.py, openpathsampling/tests/test_api.py
**ANNOUNCING THE DEV-2.0 BRANCH!**
If you have changes that must change the API, please target the `dev-2.0` branch. I'm starting that off by removing all deprecated functionality (at least, what I could find).
For most improvements and new functionality, please continue to target the default branch. Changes there will be merged into `dev-2.0` regularly. I expect that there will be several more releases of OPS (at least up to 1.6) before 2.0 is finalized.
=> Remove things deprecated for 2.0

openpathsampling/tests/test_helpers.py
Small step in the direction of #756.
I have other projects that are built on OPS (e.g., the OPS CLI). Sometimes it can be convenient to use some of the tools in `openpathsampling.tests.test_helpers`, such as `make_1d_traj`. However, `test_helpers` required importing `nose`, and so every project that used `make_1d_traj` had `nose` as a requirement just so I could get that one function, even though `nose` support in OPS is deprecated. 🙄
This fixes that situation.
(Note also that many of the functions in `test_helpers` are probably better replaced by tools in `numpy.testing`. I recommend using those rather than our own hacky implementations.)
=> Remove nose from test_helpers

openpathsampling/experimental/simstore/test_custom_json.py, openpathsampling/experimental/storage/ops_storage.py, openpathsampling/experimental/storage/test_collective_variables.py, setup.cfg
Without `simtk.unit` installed, SimStore wasn't working. We only test SimStore with full integrations (similar problem to #954).
This also adds an `extras` for SimStore, so (in future releases) `pip install openpathsampling[simstore]` will install the extra requirements for SimStore as well.
=> Fix so SimStore tests pass without simtk.unit

openpathsampling/tests/test_shooting.py
In the doc update #963, I saw from codecov that the following line was not reliably hit in `shooting.py`:
This adds a test to force that code path in the first commit: https://github.com/openpathsampling/openpathsampling/commit/1842ed9fd04bda947cba7c01f7d7016aaf9a5269
The second commit (https://github.com/openpathsampling/openpathsampling/commit/31e11bf38db860cdcec4f74561dc90ec4b614e60) drops `nose` in the `test_shooting.py` and uses `pytest` instead as an incremental update towards #756 
Edit: (https://github.com/openpathsampling/openpathsampling/pull/964/commits/dc6e428b22e106707e6fdc528fdc30e62e5ac83d) removes the duplicate of the test added in the first commit (I had copied it to a different spot around in the first commit, but forgot to remove the original one :facepalm: )
=> Make more deterministic test

examples/toy_model_mstis/README.md
When looking through the repository, I noticed that the link `404`ed
=> Fix broken link in Readme.md of toy mstis examples

README.md
Conda started trowing exceptions this morning and I wanted to see if any other builds were failing. I thought the ones here had passed (from the travis badge), but that badge has not been running for 21 days.
This PR swaps that badge to the GA one
=> Update README.md CI badge to GA

setup.cfg
With the [release of ujson 4.0.2](https://github.com/ultrajson/ultrajson/releases/tag/4.0.2), we should be able to relax the pin of ujson without regressing on #922. Since that release is very new, I'm not going to assume that it is in all distribution channels yet, so the pin is kind of complicated (still allowing ujson <2 while also allowing >=4.0.2).
By the next release, I hope we'll be able to just pin `ujson >=4.0.2`.
=> Update ujson pin

openpathsampling/numerics/histogram.py, openpathsampling/tests/test_histogram.py
This fixes an error that took a long time to track down and manifests itself with the same error as #920 (or with a wrong answer in more extreme cases).
**TLDR:** WHAMing  with more than 10 interfaces in an interfaceset was horribly broken, should now work 
https://github.com/openpathsampling/openpathsampling/commit/14bcc2f5ef927167994f737bdb31b18bd542fc88 fixes the issue and adds a regression test
https://github.com/openpathsampling/openpathsampling/commit/bf8241c3e6651d49163771152ede98131f6875e1 updates the test file to use `pytest` instead (incremental update for #756) 
How this PR came to be:
This manifested itself as the same error as #920 (partial stacktrace):
```python
IndexError                                Traceback (most recent call last)
... …
```
=> Fix broken WHAMing if an InterfaceSet has more than 10 interfaces

openpathsampling/netcdfplus/netcdfplus.py
With the release of `numpy` `1.20` came a couple `DeprecationWarning`s, mainly about `np.float` or `np.bool` just being an alias for the python internal. The one Warning that is left (in my test setup) comes from `openmmtools` and is handled in https://github.com/choderalab/openmmtools/pull/497
=> fix numpy 1.20 DeprecationWarnings

.github/workflows/tests.yml, openpathsampling/ensemble.py
There is no reason to create a new volume every time we use `AllOutXEnsemble.can_append` etc.
=> Cache AllOutX volume

openpathsampling/ensemble.py
While diving further down with #892 I saw a similar solution as #975 for `PartOutX`. This also caches that volume
=> also cache the ~volume for PartOutX

.github/workflows/tests.yml, codecov.yml
Adding [config file](https://docs.codecov.io/docs/codecovyml-reference) for CodeCov. In particular, I'm hoping that I can get CodeCov to wait until the integration tests are done before adding its comment/status indicator. It's a little annoying to get the email (which, unlike the comment, doesn't update) saying CodeCov hates the PR after only the minimal test suite has come in. Also, I keep seeing the red X on a PR and checking to see where the tests went wrong, when it's really that the tests are still running and CodeCov has incomplete info.
=> Add codecov.yml

.github/workflows/tests.yml, openpathsampling/analysis/shooting_point_analysis.py, openpathsampling/collectivevariable.py, openpathsampling/deprecations.py, openpathsampling/engines/dynamics_engine.py, openpathsampling/engines/trajectory.py, openpathsampling/sample.py
#977 dropped Python 2 from the OPS 2.0 test matrix. In the process, some code lost coverage. Here I remove the Py2-specific code for most of that (except netcdfplus, which I'm not worrying about since it will also be dropped in 2.0).
There's one line where I don't immediately understand how it lost coverage:
https://github.com/openpathsampling/openpathsampling/blob/6ff2cbbf615928c031896e1d719217d2087fa940/openpathsampling/engines/dynamics_engine.py#L256
This is in an instance test against `basestring`, but `basestring` is `str` for Py3+ (we set it at the top of the file). Any idea why that's not getting covered? (particularly @sroet)
Note that this PR is not intended to drop all Py2-related code -- there's more to do on that. This is just catching the things that lost coverage when Py2 …
=> Remove some Py2-specific code

openpathsampling/ensemble.py
Some more UUID optimization coming from #892.
So while running the test uuid system from #892, I noticed **a lot** of `Trajectory` objects getting generated. Looking at the code, **every time you slice a Trajectory, you generate a new Trajectory**.
To test how many and were I added the following code to trajectory.py (and where) 
```diff
+++ b/openpathsampling/engines/trajectory.py
@@ -23,6 +23,7 @@ class Trajectory(list, StorableObject):
"""
engine = None
+    kill_count = 1000000
def __init__(self, trajectory=None):
"""
@@ -45,6 +46,10 @@ class Trajectory(list, StorableObject):
else:
self.extend(trajectory)
+        Trajectory.kill_count -= 1
+        if Trajectory.kill_count < 0:
+            raise RuntimeError("KILLED")
+
```
and ran the following script:
```python
sset = …
```
=> Prevent excessive trajectory slicing

openpathsampling/high_level/network.py, openpathsampling/tests/test_network.py
The minus interface as set up by the `MISTISNetwork` didn't forbid the trajectory from entering other states during the excursion from the state. This would occasionally manifest as a failure of the sanity check when saving, stating that the trajectory for some replica did not satisfy the ensemble (because the trajectory in the TIS ensemble after a replica exchange had frames in the other state). 
Typically, this meant that the minus trajectory had to cross to the other state and then *cross back*, so it was extremely rare, but I found it when working on a simple model that isn't actually rare enough to really need TIS to get the rate. @gyorgy-hantal: I think you encountered this problem once. This is the explanation.
This fixes it -- everything was in place to forbid other states (and …
=> Fix MISTIS minus ensemble not forbidding other states

openpathsampling/experimental/simstore/__init__.py, openpathsampling/experimental/simstore/memory_backend.py, openpathsampling/experimental/simstore/sql_backend.py, openpathsampling/experimental/simstore/storable_functions.py, openpathsampling/experimental/simstore/storage.py, openpathsampling/experimental/simstore/test_storable_function.py, openpathsampling/experimental/simstore/test_storable_function_integration.py
This PR adds some detailed integration tests for storable functions in SimStore. These tests are considerably more complicated than the existing unit tests, and are designed to ensure that storage, backend, and storable functions play together as desired. This also fixes some problems that have previously slipped through the cracks.
A few effects of this:
* Fix issue that `StorableFunction`s didn't show up in `storage.cvs`
* Complete aspects of `MemoryStorageBackend` and `GeneralStorage` that are required to use them (instead of using the SQL backend and the OPS storage)
* Fix various issues with caching results from storable functions (either in storage or in local function cache), especially when dealing with multiple storage files.
EDIT: This also now adds support for a single storable …
=> Integration tests for SimStore StorableFunctions

openpathsampling/high_level/network.py, openpathsampling/high_level/transition.py
In MISTIS, there's a distinction between the "input transitions," "sampling transitions" and "(physical) transitions", as described here:
https://github.com/openpathsampling/openpathsampling/blob/d32c198fc014d26d31ff8c62a8f9fa65ff3049c9/openpathsampling/high_level/network.py#L742-L750
However, OPS was auto-naming input transitions (and associated ensembles) with the same names as sampling transitions, potentially causing confusion when trying to load from storage. This PR fixes that by adding a `name_suffix` to the transitions, which defaults to an empty string. For input transitions, we use `name_suffix=" (input)"`.
=> Fix problem with repeated ensemble names in MISTIS

examples/ipynbtests.sh, examples/tests/test_cv.ipynb, examples/tests/test_netcdfplus.ipynb, examples/tests/test_openmm_integration.ipynb, examples/tests/test_pyemma.ipynb, examples/tests/test_snapshot.ipynb, examples/toy_model_mistis/toy_mistis_1_setup_run.ipynb, examples/toy_model_mistis/toy_mistis_3_analysis.ipynb, examples/toy_model_mstis/toy_mstis_2_run.ipynb, examples/toy_model_mstis/toy_mstis_3_analysis.ipynb, setup.cfg
We currently run several notebooks as tests -- mostly system-scale smoke tests, though also some more unit-level testing. These tests are run using a tool that @jhprinz wrote, [ipynbtest](https://github.com/jhprinz/ipynb-test).
Unfortunately, ipynbtest hasn't been maintained for a quite a while. Additionally, after @jhprinz developed ipynbtest, another tool, [nbval](https://github.com/computationalmodelling/nbval), became a widely used pytest plugin for using Jupyter notebooks in testing.
With no one to maintain ipynbtest, I think we need to switch to nbval. This PR does that. I'm sad about this, because I think ipynbtest is a nicer tool to use (I like the way it reports Markdown headings as a progress indicator while running.) However, this is now the only thing blocking us from testing …
=> Switch notebook tests to nbval

codecov.yml
Some recent PRs that should have no effect on coverage (#990, #984) have been getting complaints from CodeCov because a single line in netcdfplus has become uncovered (not sure if this is flakiness or a change in something upstream).
This PR adds a threshold so CodeCov will pass if flakiness uncovers up to 0.4% of the currently covered code. That corresponds to about 5 Python statements.
This only affects the CodeCov "project" check: the "patch" check will keep its default behavior, which is that coverage for lines changed in the PR must be at least as much as the current total project coverage.
=> Add threshold to codecov.yml

openpathsampling/experimental/simstore/storable_functions.py, openpathsampling/experimental/simstore/test_storable_function.py, openpathsampling/experimental/storage/collective_variables.py
This PR adds information about periodicity to SimStore CVs. It reserves the kwargs `period_min` and `period_max`.
This isn't currently used anywhere in the core of OPS, but might be used in the future to combine `PeriodicCVDefinedVolume` and `CVDefinedVolume` (probably a good option for OPS 2.0).
It will be used in the CLI for simulation setup.
=> SimStore: Periodic CVs

devtools/experimental_reqs.txt, setup.cfg
Tests stopped working this morning (had to be the day of my APS March Meeting talk!) SQLAlchemy accidentally made changes in their 1.4.0 release that broke SimStore. See https://github.com/sqlalchemy/sqlalchemy/issues/6074. Looks like they're already preparing a fix, so I'm pinning to `!=1.4.0` as opposed to `<1.4`.
=> Pin sqlalchemy!=1.4.0

openpathsampling/experimental/storage/ops_storage.py
Previously, `storage.cvs` contained all the storable functions. It should only include CVs (which are specifically storable functions that take a snapshot as input). This PR fixes that issue.
=> SimStore storage.cvs should only be CVs

examples/tests/test_pyemma.ipynb
I've been having problems with PyEMMA tests being flaky in Py2.7 ever since #987. It seems like there's something that sometimes shows up in stderr, which ipynbtest didn't check but apparently nbval does. The error I get is:
```
Notebook cell execution failed
Cell 8: Cell outputs differ
Input:
cv(storage.trajectories[0]);
Traceback:
Unexpected output fields from running code: set([u'stderr'])
```
This PR adds ignores to that cell and another near it that also may cause problems.
=> Potential fix for flaky PyEMMA tests in 2.7

openpathsampling/engines/openmm/engine.py, openpathsampling/engines/openmm/features/instantaneous_temperature.py, openpathsampling/engines/openmm/tools.py, openpathsampling/engines/toy/engine.py, openpathsampling/engines/toy/features/instantaneous_temperature.py, openpathsampling/snapshot_modifier.py, openpathsampling/tests/test_openmm_engine.py, openpathsampling/tests/test_snapshot_modifier.py, openpathsampling/tests/test_toy_dynamics.py
This moves the calculation of the number of degrees of freedom to the engine. This is expected to be a constant for an engine -- at least, the engines we have so far don't allow number of particles to change -- so it makes sense to cache it (for OpenMM), instead of calculating it over and over with the `snapshot.n_degrees_of_freedom` feature.
This also adds an `engine.has_constraints()` method. This gives a cleaner way to abort if an engine with constraints tries to use one of the `DirectionModifier` snapshot modifiers.
=> Move n_dofs to engine; add engine.has_constraints()

openpathsampling/tests/test_shooting.py
This week my CI failed with:
```python
=================================== FAILURES ===================================
______________________ TestGaussianBiasSelector.test_pick ______________________
self = <openpathsampling.tests.test_shooting.TestGaussianBiasSelector object at 0x7fac57d4fc10>
def test_pick(self):
picks = [self.sel.pick(self.mytraj) for _ in range(100)]
pick_counter = collections.Counter(picks)
assert set(pick_counter.keys()) == set(range(len(self.mytraj)))
>       assert pick_counter[2] > pick_counter[0]
E       assert 13 > 18
openpathsampling/tests/test_shooting.py:70: AssertionError
```
(first mentioned in #998) from the comments on #998, this test should just be made less flaky.
timing for this test file goes from `1.06 s` to `1.10 s` with this change
=> make test less flaky

openpathsampling/experimental/simstore/attribute_handlers.py, openpathsampling/experimental/simstore/custom_json.py
Removes some old `tostring()` calls that should be `tobytes()`.
=> Fix SimStore NumPy deprecations

.github/workflows/tests.yml, codecov.yml, devtools/ci/miniconda_install.sh, examples/ipynbtests.sh, examples/misc/tutorial_storage.ipynb, examples/prep_example_data.py, setup.cfg
OpenMM and OpenMMTools are now available on conda-forge (and therefore available for Python > 3.7). Resolves #864.
Because we release via conda-forge, we already release on 3.8 and 3.9, but they haven't been in our test matrix on CI.
=> Add Python 3.8, 3.9 to testing matrix

openpathsampling/__init__.py, openpathsampling/pathmover.py, openpathsampling/pathmovers/spring_shooting.py, openpathsampling/random.py, openpathsampling/sample.py, openpathsampling/shooting.py, openpathsampling/tests/test_pathmover.py, openpathsampling/tests/test_random.py, openpathsampling/tests/test_shooting.py
This week my CI failed with:
```python
=================================== FAILURES ===================================
______________________ TestGaussianBiasSelector.test_pick ______________________
self = <openpathsampling.tests.test_shooting.TestGaussianBiasSelector object at 0x7fac57d4fc10>
def test_pick(self):
picks = [self.sel.pick(self.mytraj) for _ in range(100)]
pick_counter = collections.Counter(picks)
assert set(pick_counter.keys()) == set(range(len(self.mytraj)))
>       assert pick_counter[2] > pick_counter[0]
E       assert 13 > 18
openpathsampling/tests/test_shooting.py:70: AssertionError
```
This PR attaches a random number generator to the selectors that can be seeded during tests to prevent these flaky tests.
The current implementation requires `numpy>=1.17` (that is …
=> Add global random number generator; support in shooting pt selectors and pathmovers

openpathsampling/netcdfplus/base.py
As of #995, it appears that netcdfplus tries to load CVs as SimStore CVs. This is apparently because netcdfplus maps a class name (not fully qualified; just the class name) to a class. And once SimStore CVs were found in the chain of subclasses, netcdfplus replaced the old CVs with the new ones. This would lead to errors when loading old CVs (which do not have the same storage dict as new CVs).
The solution is to exclude classes in the `openpathsampling.experimental.storage` subpackage from being listed as classes that netcdfplus can load.
=> Prevent netcdfplus from trying to load netcdfplus CVs as SimStore CVs

openpathsampling/experimental/simstore/storable_functions.py, openpathsampling/experimental/simstore/test_storable_function.py
The definition of modes for storable functions in SimStore (i.e., `'analysis'`, `'production'`, `'no-caching'`) was in a dictionary that was defined in the `__call__` method. This moves that dictionary to a private instance variable. This will allow (advanced) users to update that dictionary with custom modes.
This also removes an unnecessary skip that was shadowing the fact that some tests needed to be updated for changes in #985. The previously skipped tests now run and pass.
=> SimStore: Make storable function modes customizable

openpathsampling/pathmovers/spring_shooting.py, openpathsampling/shooting.py
closes #1007 (partly)
The notebook from that issue now works. However, It is now uncertain is the state of the generators that is loaded. 
This depends whether OPS is re-imported between loading or not.
```python
{'bit_generator': 'PCG64',
'state': {'state': 336467696170254096309584224979479325155,
'inc': 238122374084886836437703854582102603205},
'has_uint32': 0,
'uinteger': 0}
<numpy.random._pcg64.PCG64 at 0x7f0b819d9d10>
{'bit_generator': 'PCG64',
'state': {'state': 195230481313007235580189205770362297672,
'inc': 238122374084886836437703854582102603205},
'has_uint32': 1,
'uinteger': 2214207804}
<numpy.random._pcg64.PCG64 at 0x7f0b819d9d10>
{'bit_generator': 'PCG64',
'state': {'state': 195230481313007235580189205770362297672,
'inc': 238122374084886836437703854582102603205},
'has_uint32': …
```
=> make rng private for selectors

examples/tests/test_pyemma.ipynb
Adds another ignore cell output (stderr) to the flaky PyEMMA notebook.
Honestly, it's probably best to just convert that notebook to proper unit tests. We need the unit tests anyway, and that's the main purpose of that notebook.
Such a minor change -- will merge on green.
=> Ignore more flaky PyEMMA on Python 2.7

openpathsampling/collectivevariable.py, openpathsampling/collectivevariables/plumed_wrapper.py, openpathsampling/engines/openmm/engine.py
A student asked my help initializing the `OpenMMEngine` and I could not find the `openpathsampling.engines.openmm.MDTopology`. Looking at `openpathsampling/engines/openmm/topology.py` this is actually called: `MDTrajTopology`
This PR all the docstrings that mention `MDTopology`. 
it also fixes some of the trivial `pep8` complaints in openmm/engine.py
=> Fix docstring MDTopology to MDTrajTopology

openpathsampling/engines/openmm/__init__.py
This fixes a backward compatibility problem introduced in #1012:
```python
import openpathsampling as paths
paths.engines.openmm.topology.MDTrajTopology
```
After #1012:
```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-95752f96565c> in <module>
----> 1 paths.engines.openmm.topology.MDTrajTopology
AttributeError: module 'openpathsampling.engines.openmm' has no attribute 'topology'
```
After this PR:
```
/Users/dwhs/miniconda3/envs/dev/bin/ipython:1: DeprecationWarning: openpathsampling.engines.openmm.topology.MDTrajTopology has been moved. Import MDTrajTopology from openpathsampling.engines instead.
#!/Users/dwhs/miniconda3/envs/dev/bin/python
```
=> Fix backward compatiblity for MDTrajTopology

devtools/tested_integrations.txt
A change in OpenMM 7.5.1 is causing our tests to fail, and could cause problems for users if they trigger a NaN during dynamics with OpenMM. See https://github.com/openmm/openmm/issues/3098.
=> Pin OpenMM != 7.5.1

examples/tests/test_pyemma.ipynb
This failed for 2.7 with:
```
__________________ examples/tests/test_pyemma.ipynb::Cell 10 ___________________
Notebook cell execution failed
Cell 10: Cell outputs differ
Input:
py_cv = storage.cvs['pyemma']
Traceback:
Unexpected output fields from running code: set([u'stderr'])
```
Fixed in a similar fashion as #1009 
[edit]: [link to the failing test](https://github.com/sroet/openpathsampling/runs/2515098923)
=> ignore more flaky pyemma py 2.7

.github/workflows/check-openmm-rc.yml, .github/workflows/test-openmm-rc.yml
Every time I see an OpenMM release candidate announced, I think, "I should really try that out and run the OPS test suite against it." But I don't. And this time we got hit by a bug (https://github.com/openmm/openmm/issues/3098) that could have been fixed in prerelease had I run those tests.
So the other day I created a GitHub Action that checks for recent prereleases of a conda package. This PR is to implement use of it here. I think I'll need to merge this PR before I can actually check that everything works, because the workflow that gets triggered to run the tests won't exist until it has been merged to master. So this may require a follow-up PR to complete everything, although the basic idea seems to be working fine in https://github.com/dwhswenson/conda-rc-check/.
Overall approach I …
=> Test against OpenMM RCs

.github/workflows/test-openmm-rc.yml
I used the wrong trigger name in #1019. (I had also looked at using the `repository_dispatch` mechanism, but decided to use `workflow_dispatch` instead.)
I'm merge this as soon as tests pass.
=> Fix error in testing OpenMM RCs

.github/workflows/check-openmm-rc.yml
I got the expected failure with `ndays` set to 30, so this PR is just to reduce that down to 3. See #1019 for overall test design.
I'll merge this immediate on passing tests; all needed review was done in discussion of #1019.
=> OpenMM RC testing: Switch ndays to 3

examples/tests/test_pyemma.ipynb
Similar to #1018 , I know the drill by now.
Today py2.7 failed with:
```
=================================== FAILURES ===================================
__________________ examples/tests/test_pyemma.ipynb::Cell 15 ___________________
Notebook cell execution failed
Cell 15: Cell outputs differ
Input:
py_cv_idx = storage.idx(py_cv)
print(py_cv_idx)
py_emma_feat = storage.vars['attributes_json'][py_cv_idx]
Traceback:
Unexpected output fields from running code: set([u'stderr'])
```
This also ignores that cell
=> ignore cell 15 pyemma test

README.md
We're still showing the old Coveralls badge, which hasn't updated since last year. This updates the badge to Codecov, which we're actually using.
=> Switch README to Codecov badge

docs/shooting.rst, openpathsampling/__init__.py, openpathsampling/shooting.py, openpathsampling/tests/test_shooting.py
For a very long time, OPS has had the ability to use a Gaussian bias in shooting point selection. That is, given a CV `f`, the  probability of selecting a shooting point `x` within a given trajectory is proportional to `np.exp(-a*(f(x)-x0)**2)`, where `a` and `x0` are parameters set by the user.
There is no reason for this to be restricted to Gaussians. This PR introduces a `BiasedSelector`, which allows one to use *any* function (wrapped in an OPS CV) as the bias function. The only reason this didn't exist before is because when we were writing shooting point selectors, I don't think we understood the flexibility that OPS CVs would have. 
Now, for example, the `GaussianBiasSelector` could be implemented as:
```python
def gaussian(snapshot, cv, a, x0):
return np.exp(-a * …
```
=> Shooting point selector with arbitrary bias

openpathsampling/experimental/storage/monkey_patches.py, openpathsampling/experimental/storage/test_pathsampling.py, openpathsampling/pathsimulators/path_sampling.py, openpathsampling/tests/test_pathsimulator.py
Based on an email report from @gyorgy-hantal. It seems that SimStore was not saving the move scheme in the rare case that all steps fail due to maximum length/NaN. This seems to be because of a difference in SimStore allowing you to stash several steps for saving, whereas netcdfplus immediately saves after each step.
This PR also introduces a (not well-tested) `unpatch` method to undo the SimStore monkey patches. This will mainly be useful in testing.
=> Ensure that SimStore always saves movescheme

openpathsampling/experimental/simstore/sql_backend.py, openpathsampling/experimental/simstore/test_sql_backend.py
This converts the `max_query_size` that @sroet had introduced as an instance variable in `SQLStorageBackend` to a class variable, and adds its use in a corner case that @gyorgy-hantal came across.
It makes more sense to have this as a class variable because it is determined by the way the SQL backend (usually SQLite) was compiled on the local machine, and therefore will be constant throughout a session (for however many files the user opens). Of course, it can still be overridden on an instance-by-instance basis.
Currently WIP because I'm hoping that I can get a regression test, but I may mark it as ready to merge without such a test if it is too annoying to create. @gyorgy-hantal has confirmed that this fixed his issue.
=> MAX_SQL_ITEMS as class variable

openpathsampling/numerics/histogram.py, openpathsampling/tests/test_histogram.py
Issue found by a master student:
If `cv` singletons are not unpacked the `SparseHistogram` might return broken output bins, which then fail in following code that assumes it is 1D (Like in [this line](https://github.com/openpathsampling/openpathsampling/blob/aaff2b8e41cf42a13bbb5ce55a498ff66d03e8c6/openpathsampling/analysis/path_histogram.py#L210)).
This PR forces a reshape to prevent mangled output
master:
```python
>>> from openpathsampling.numerics.histogram import SparseHistogram
>>> histo = SparseHistogram(bin_widths=(0.5, 0.3), left_bin_edges=(0.0, -0.1)) 
>>> data = ([0.0],[1.0])
>>> histo.map_to_bins(data)
(array([0., 0.]), array([2., 3.]))
>>> max(histo.map_to_bins(data))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: The truth value of an …
```
=> Make histogramming more robust

openpathsampling/beta/hooks.py, openpathsampling/pathsimulators/path_sampling.py, openpathsampling/step_visualizer_2D.py, openpathsampling/tests/pathsimulators/test_hooks.py
This builds on #755 and should only be merged after that.
It adds hook support to the `PathSampling`, the `PathSamplingOutputHook` and the `LiveVisualizerHook` including tests.
Please let me know if htere is anything to improve!
I also have some open questions/TODOs, in particular:
1. if a user sets any attribute that controls the behaviour of the hook on the `PathSimulator` object it is only read once at the start of the simulation and only if the hooks value for that attribute is `None` (see e.g. `output_stream`, `save_frequency` and `storage`). This is potentially confusing, as I would expect to be able to set these attributes on the `PathSimulator` to influence the behaviour of the currently attached hooks. I am mot really sure how to adress this. Potential solutions include removing …
=> "Hooks" for PathSampling

openpathsampling/beta/hooks.py, openpathsampling/tests/pathsimulators/test_hooks.py
This builds on #911 and #755. It should only be merged after them. 
This adds a `GraciousKillHook` that writes the current simulation state to storage and ends the simulation loop by raising a `GraciousKillError` when a given maximum walltime is reached.
You can also pass a custom callable as `final_call` at hook construction, in case you want to do anything else than closing the storage when the simulation is terminated.
Example usage (assuming your steps are not superfast the code below should end the simulation after something sligthly smaller than 3 min 34 s):
```python
kill_hook = GraciousKillHook("3 minutes 34 seconds")
sampler.attach_hook(kill_hook)
try:
sampler.run(2000)
except GraciousKillError:
print("Simulation ended due to maximum walltime reached")
```
=> Gracious kill hook

openpathsampling/numerics/lookup_function.py
The test suite gave the following future warning:
```python
openpathsampling/tests/test_lookup_function.py::TestVoxelLookupFunction::test_df_2d
/home/sroet/github_files/openpathsampling/openpathsampling/numerics/lookup_function.py:268: FutureWarning: In a future version of pandas all arguments of DataFrame.sort_index will be keyword-only
df = df.sort_index(0).sort_index(1)
```
066f87a implements the fix for that (make the arguments keyword based instead of location based).
90c75cf solves the `pep8` complaints my coding environment was noticing
=> Fix DataFrame.sort_index future warning

openpathsampling/deprecations.py, openpathsampling/experimental/simstore/class_info.py, openpathsampling/experimental/simstore/memory_backend.py, openpathsampling/experimental/simstore/regressions/README.md, openpathsampling/experimental/simstore/regressions/test_numpy_sfrs.py, openpathsampling/experimental/simstore/serialization.py, openpathsampling/experimental/simstore/sql_backend.py, openpathsampling/experimental/simstore/storable_functions.py, openpathsampling/experimental/simstore/storage.py, openpathsampling/experimental/simstore/test_sql_backend.py, openpathsampling/experimental/simstore/test_storable_function.py
There was a bug when storing results from SimStore CVs that were not types known to SQL (mainly, if the result of a CV was a NumPy array). Essentially, the result type of CVs were not being stored to the file.
This PR fixes it. This does make some changes to the interface for backends (they must define `serialization` and `sfr_result_types` dictionaries, and the entry in `sfr_result_types` for a given storable function must be set during the `register_storable_function` method). It's unlikely that anyone is writing custom backends, but this would affect such users.
---
For any users affected by this bug: Your data is still intact, you just need to tell SimStore how to load it. I've saved a [notebook to a gist](https://gist.github.com/dwhswenson/88d672a7258e646de192dd4af5810869) …
=> Fix bug with SimStore CVs storing NumPy arrays

openpathsampling/tests/test_external_engine.py
When I looked at the tests in #1043, I noticed a:
```
/home/runner/work/openpathsampling/openpathsampling/openpathsampling/tests/test_external_engine.py:48: SyntaxWarning: "is" with a literal. Did you mean "=="?
if line is '':
```
This solves that warning, drops `nose` from that particular test file (part of #756), and solve some style complaints
=> Fix syntax warning

openpathsampling/experimental/simstore/my_types.py, openpathsampling/experimental/simstore/sql_backend.py, openpathsampling/experimental/simstore/test_sql_backend.py, openpathsampling/experimental/simstore/type_ident.py, openpathsampling/experimental/simstore/uuids.py, openpathsampling/experimental/storage/simtk_unit.py
I tried reading a file that did not exist in that directory, this lead to 2 things happening:
1) the file was created (this made it so that it took way too long before I figured out what was going on)
2) the code failed with: 
```
~/github_files/openpathsampling/openpathsampling/experimental/simstore/sql_backend.py in __init__(self, filename, mode, sql_dialect, **kwargs)
148             )
149             engine = sql.create_engine(self.connection_uri, **self.kwargs)
--> 150             self._initialize_from_engine(engine)
151             self.mode = mode  # in case we changed when checking existence
152 
~/github_files/openpathsampling/openpathsampling/experimental/simstore/sql_backend.py in _initialize_from_engine(self, engine)
154         self.engine = engine
155         self._metadata …
```
=> Raise FileNotFoundError if sql backend tries to read a file that does not exist

.github/workflows/test-2.0.yml, examples/ipynbtests.sh
The main development branch CI is in `.github/workflows/tests.yml`. The CI for the 2.0 development branch is in `.github/workflows/test-2.0.yml`. This PR ports improvements in `tests.yml` into `test-2.0.yml` (and, of course, targets the `dev-2.0` branch).
Useful improvements:
* Adds Python 3.8 and 3.9 to the test suite. This wasn't possible (no OpenMM available) before.
* Adds notebook tests. I'm not sure why this wasn't done before, but with core changes on the way, such as #1042, I'll feel a lot better having the more thorough test suite.
=> Update CI for OPS 2.0

openpathsampling/analysis/shooting_point_analysis.py, openpathsampling/tests/test_shooting_point_analysis.py
A student tried to use ShootingPointAnalysis on a comittor simulation. However, due to the nature of his (biological) system, some of the steps were rejected due to reaching maximum length.
He thus ran into the (leftover) AssertionError.
This PR cleans up that error handling and adds an option to skip rejected steps:
e46fe67 adds the functionality and tests
2a529c4 solves a pep8 complaint from my coding environment
37e5428 drops nose from the test file and cleans up some unnecessary compatibility code (this test file should be inspected again when dropping python 2.7)
For 2.0 I would propose to break API and change the default of `skip_rejected` to `True`. (I think that rejected steps should not be included in analysis on default).
=> Prevent errors in ShootingPointAnalysis with invalid (e.g., max length) trajectories

openpathsampling/analysis/shooting_point_analysis.py
This changes the Error type of the ShootingPointAnalysis from an `AssertionError` (to ensure backwards compatability) to an more reasonable ~`ValueError`~ `Exception` for OPS 2.0. 
(I could not figure out how to do an easy DeprecationWarning on this; My current guess would be to write a metaclass that would update the MRO/`__bases__` of this error to a subclass of tuple that would warn if the index that contained the `AssertionError` was accessed, something like [this SO answer](https://stackoverflow.com/a/20832588/15100302)) 
Edit: this also merges the current master into OPS 2.0
Edit 2: after 2d95011 this now becomes an `Exception` instead of a `ValueError`
=> Change ShootingPointAnalysisError to an Exception

.github/workflows/check-openmm-rc.yml, .github/workflows/test-openmm-rc.yml, openpathsampling/__init__.py, openpathsampling/engines/features/shared.py, openpathsampling/engines/features/statics.py, openpathsampling/engines/gromacs/__init__.py, openpathsampling/engines/gromacs/engine.py, openpathsampling/engines/openmm/__init__.py, openpathsampling/engines/openmm/engine.py, openpathsampling/engines/openmm/features/__init__.py, openpathsampling/engines/openmm/features/instantaneous_temperature.py, openpathsampling/engines/openmm/features/masses.py, openpathsampling/engines/openmm/features/traj_quantities.py, openpathsampling/engines/openmm/tools.py, openpathsampling/engines/topology.py, openpathsampling/experimental/storage/simtk_unit.py, openpathsampling/experimental/storage/test_simtk_unit.py, openpathsampling/integration_tools.py, openpathsampling/netcdfplus/dictify.py, openpathsampling/netcdfplus/netcdfplus.py, openpathsampling/snapshot_modifier.py, openpathsampling/tests/test_helpers.py, openpathsampling/tests/test_integration_tools.py, openpathsampling/tests/test_openmm_engine.py, openpathsampling/tests/test_openmm_tools.py, openpathsampling/tests/test_snapshot_modifier.py, openpathsampling/tests/test_volume.py, openpathsampling/volume.py
Good news: the [GitHub action I wrote](https://github.com/marketplace/actions/check-conda-for-release-candidates) to automatically test against OpenMM release candidates works! The tests ran against the newest RC.
Bad news: we explode with errors on the 7.6 RC. This is because the OpenMM import has moved out of the `simtk` namespace (so it is now correct to do `import openmm`; `import openmm.unit`). The old imports still work for the `simtk.openmm`, `simtk.openmm.app`, and `simtk.unit` namespaces. However, we were also using some OpenMM internals (specifically, `simtk.openmm.app.internal.unitcell.reducePeriodicBoxVectors`.) Importing from these does not work.
This PR fixes that, and makes the non-`simtk` import the preferred choice.
=> Fixes for OpenMM 7.6 RC

openpathsampling/tests/test_external_engine.py
@bdice identified an issue with our tests leaving files around after running the test. This is bad test design and should be avoided.
This PR fixes the offending test
=> Remove engine binary after tests

CITATIONS.md
closes #1063 
The current [citation file format](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md) does not seems to be able to handle more than 1 citation and OPS is normally cited with 2 (at least for 1.x)
However, github allows for [other citation files](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files#other-citation-files) which are then be linked to (I still have to check in what way exactly)
I therefor opted to go for the current text on the website about citation, but altered it to markdown instead of rst
=> Add CITATIONS.md

openpathsampling/experimental/storage/monkey_patches.py
There's an `unpatch` method in the `monkey_patches` to undo the patches that tell OPS that you'll be using SimStore. This generally isn't used by users (who tend to be either fully in SimStore or fully not, at least within a given session), but it is important for unit testing.
This PR adds some `importlib.reload` commands that are required to fully undo the patch.
=> improvements to unpatch after using SimStore

.github/workflows/tests.yml, devtools/conda_install_reqs.sh, openpathsampling/tests/test_reactive_flux_analysis.py
Third (and, I hope, final!) version of this. See also #1072 and #1071 for the history of trying to debug this problem.
Main points, quoting from previous:
> Py27 builds have taken too long for a while, and now they're so bad that they're failing CI. (20+ minutes was bad, but then it jumped to 2 hours -- and now it takes more than 6 hours?!?!?!) I don't know why this is getting worse, but this is insane.
> 
> In this PR, I'm going to try to switch to [mamba](https://github.com/mamba-org/mamba). I've personally been using mamba for a while now. I tested locally and could build a Py27 environment for OPS in a few minutes, using the same command that hangs in CI. (The conda version of the same command is _still_ trying to run -- the problem isn't with GitHub actions, since it affects me, …
=> Switch CI install to mamba

openpathsampling/deprecations.py, openpathsampling/pathmovers/spring_shooting.py, openpathsampling/shooting.py, openpathsampling/tests/test_shooting.py
From writing down the code in [this comment](https://github.com/openpathsampling/openpathsampling/pull/1075#issuecomment-935750466) I noticed that selector.probability_ratio might not properly work for snapshots that get their coordinates altered.
- `selector.probability_ratio` takes a frame, normally the original selected shooting point, the original trajectory, and a new trajectory
-  that frame can be modified before generating the new trajectory, which would lead to the situation that new_traj.index(frame) raises a `ValueError` if the coordinates were modified
- the added test in 3ad2cc3 shows that this behaviour indeed fails
- `Trajectory` objects are essentially `list`s and inherits their way of checking for 'index'
- ~~`Trajectory.index(snapshot)` looks at the `hash`es of all …
=> Take care of coordinate modifcation in selector probability_ratio  

openpathsampling/deprecations.py, openpathsampling/pathmover.py, openpathsampling/snapshot_modifier.py, openpathsampling/tests/test_pathmover.py, openpathsampling/tests/test_shooting.py, openpathsampling/tests/test_snapshot_modifier.py, openpathsampling/tests/test_spring_shooting.py
Closes #794 for all OPS classes
However, a new issue should be opened to discuss a refactor of `EngineMover` to take this and the other bias options [described in this comment](https://github.com/openpathsampling/openpathsampling/issues/794#issuecomment-923830025) into account for OPS 2.0.
Custom implementations of both `EngineMover` and `SnapshotModifier` should tyake care to implement this correctly on their end.
Big assumption (that might break API): **A key that starts with "bias" should not be present in `run_details` if it is not intended to be used for the bias calculation of a sample** 
todo:
commit descriptions:
4f017dd adds probability_ratio to snapshot modifiers
ad7fad0 allows the usage of this probability ratio to be used as a bias in EngineMovers
0e42bb9 reverts an oversight …
=> Account for modifier acceptance in engine movers

openpathsampling/engines/features/box_vectors.py, openpathsampling/experimental/storage/test_snapshot_integrations.py
This fixes a bug when using `engines.features.box_vectors` in SimStore. Previously, these were not saved.
As far as I can tell, this bug only occurs if you are using the internalized Gromacs snapshots, introduced in #933, and storing them with the new SimStore storage system. (However, it could be an issue for engines that aren't included in core OPS.) The OpenMM engine uses a box vectors feature in `engines.features.statics` and the Gromacs engine uses a box vectors feature in `engines.external_snapshots.features.box_vectors`, so neither of these are affected. I only found this bug when I was going to suggest using SimStore + internalized snapshots as part of a [user question](https://mattermodeling.stackexchange.com/questions/6967/) that came up today. It seems that I overlooked this …
=> SimStore: Fix issue with internalized snapshot box vectors

docs/copyfiles/copyfiles.py, docs/copyfiles/notebooks.yml
In order to move notebooks into the right locations, a while ago I added a `copyfiles` script to our docs directory. This is specifically used to bring our docs from examples into the docs, where Sphinx can find them.
Today, I discovered that it was using GitLab to download (very outdated) copies of our tutorial notebooks. So I updated the script to allow us to use GitHub instead.
Then I realized that I we're not even *using* those downloaded notebooks in our docs. 🤷‍♂️ It definitely makes more sense to just *link* to the repositories, especially given the option of launching the tutorial with Binder.
In any case, I left the addition of support for GitHub, and removed the downloads of the tutorial notebooks from online (this also would have been an annoyance to anyone trying to build our …
=> DOCS: Add GitHub support to `copyfiles`, remove online notebook downloads

openpathsampling/experimental/simstore/storable_functions.py, openpathsampling/experimental/simstore/test_storable_function.py
This fixes a bug in SimStore storable functions serialization. When support for function periodicity was added in #990, it looks like I failed to add the periodicity information to the `StorableFunction.to_dict`. This fixes that, and includes a test to prevent regression.
Currently, function periodicity is only used by the (as yet unreleased) command line tools for setting up a simulation, where it is only used at object creation time to determine whether a volume should be periodic or not. This means that the only use case where this bug could be a problem would be if the user is using the unreleased CLI `wizard` to create *new* volumes for periodic CVs *after* loading that CV from a file. This is an unlikely use case, so I don't think this is a critical concern, but it does push for an …
=> SimStore: Fix storable function serialization

.github/workflows/autorelease-default-env.sh, .github/workflows/autorelease-deploy.yml, .github/workflows/autorelease-gh-rel.yml, .github/workflows/autorelease-prep.yml
Autorelease 0.3.2 was released back in August. The main improvements are in blocking Autorelease workflows from running on forks (see #1061, #1062) and in better information on the vendored files (to ensure that the status as vendored from Autorelease is more clear).
=> Bump to Autorelease 0.3.2

docs/install.rst
This PR is a rewrite of the installation page of the docs. The old installation page was originally written with the expectation that we'd need to onboard new contributors who had very little Python experience, and that we'd want to give them multiple options for how to get OPS installed.
However, the install docs are one of the first pages *users* come to. So I've re-written them to be more focused on user concerns. I kept a brief mention of installing by pip/setuptools, but basically assume that if you're doing that, you know what you're doing.
The new docs include also discuss various tools within the molecular simulation ecosystem that OPS integrates with, and they emphasize that all you need to do to get OPS to work with those tools is install them on your system.
Docs-only; this …
=> Docs: New Installation docs

.github/workflows/test-openmm-rc.yml
Our automated check against new OpenMM release candidates picked up a new RC last night, and the build [is failing](https://github.com/openpathsampling/openpathsampling/runs/4517804647?check_suite_focus=true) with a conda `UnsatifiableError`. I'm going to try to fix this on our side. Among other things, it seems like there's a weird combination trying to pull in `python=3.10` while also pulling in `pypy3.6`, which seems like an obvious source of conflict. We don't currently test against 3.10, so I'm guessing that's the issue (this fails before we try to install the OpenMM RC, so I suspect the problem due to changes in the GitHub Actions environment, not due to the RC itself).
I'll do a little on this now, but if my first tries don't solve, I'll come back to it later in the day (after …
=> Fix build for OpenMM RCs

openpathsampling/engines/toy/pes.py
This fixes a DeprecationWarning that popped up in the running tests after merging #787 
```
openpathsampling/engines/toy/pes.py:374
/home/sroet/github_files/openpathsampling/openpathsampling/engines/toy/pes.py:374: DeprecationWarning: invalid escape sequence \s
"""Simple double-well potential. Independent in each degree of freedom.
```
=> make a missed string into a rawstring

.github/workflows/check-openmm-rc.yml
We're currently using the `@main` branch of the `check-openmm-rc` GitHub action. This is not a best practice, because (1) it does not guarantee a stable API, and (2) a bad actor could change that action and potentially abuse our resources.
I'm not actually terribly worried about either (since I maintain the action, I would update here if I broke the API). However, @mikemhenry came across what seems to be a broken `@v1` tag on that, so I thought I'd try to figure out how to fix it here.
My goal is to get this to work with a "stable API" approach, where the `@v1` tag will work. The most secure approach is to pin to a specific commit (usually the commit associated with a specific tag). We probably won't worry about that here, because GH actions is well compartmentalized and it shouldn't be …
=> Move check-openmm-rc off of main branch

openpathsampling/deprecations.py, openpathsampling/engines/external_engine.py, openpathsampling/tests/test_external_engine.py
this adds a `FutureWarning` to let users know that in OPS 2.0 the default `FileSetter` will become random string
This was part of the discussion on #1101
=> Add FutureWarning for default filesetter external engines

openpathsampling/shooting.py, openpathsampling/tests/test_shooting.py
After 5 years of using ops it bit me today, for the old implementation it was possible to have `idx == len(prob_list)` in the last iteration which would then raise an `IndexError` when trying to get the associated probability from prob_list. 
Or in other words in 5 years of ops I never tried to select the last frame of a trajectory as new shooting point, which is a good thing I would say :)
EDIT: typo
=> Improved implementation of shooting point selector pick (avoid model that might introduce index error in subclasses)

openpathsampling/experimental/simstore/callable_codec.py, openpathsampling/experimental/simstore/test_callable_codec.py
Resolves #1112.
This should at least get tests working. I'm keeping an eye on https://github.com/uqfoundation/dill/issues/482 / https://github.com/uqfoundation/dill/pull/486 for possible better long-term fixes, although it might make sense to just leave this as-is. Serialization of callables shouldn't be a performance bottleneck for us, so as long as this works, I'm not worried if this might be a little slower.
=> (Possible temporary) Fix dill in testing

LICENSE, docs/conf.py
Happy new year!
This updates the copyright I found with `grep -rl "2021" ./ --exclude=*.{pdb}`
=> update copyright to 2022

examples/tests/test_openmm_integration.ipynb
with openmmtools `0.21.0` released this guard against the import warning introduced in #1091 is not needed anymore
=> revert openmmtools import guard from test notebook

openpathsampling/experimental/storage/monkey_patches.py, openpathsampling/experimental/storage/test_monkey_patches.py
It was possible to double monkey-patch for the experimental storage. This caused many headaches downstream (e.g., OPS CLI) because that meant that something downstream had to track state of whether OPS had been monkey-patched. It also might be the problem behind #1108. This PR makes it so that monkey-patching is idempotent.
Marked WIP because it still needs tests (which will be slightly a pain), but this is the implementation I'm planning on.
=> Prevent double monkey-patching experimental storage

openpathsampling/experimental/storage/ops_storage.py, openpathsampling/experimental/storage/test_regressions.py
Well this is an embarrassing bugfix to have missed for so long. @sroet, could you spare 30 seconds to review my fix of this facepalm?
I will merge this immediately after review or after it sits open for over 24 hours, merging around Tue 02 Aug 23:00 GMT (18:00 my local).
@ShenWenHuibit: This should fix the current problem you're having. If you can do a developer install using the fork `dwhswenson` and branch `use-mdtraj-codec`, you should be able to try it out immediately.
=> Use MDTraj codecs in SimStore JSON serialization

setup.cfg
Looks like recent failures in CI are because of a numpy/numba incompatibility. See https://github.com/numba/numba/issues/8615. Should be fixed soon, but hopefully this pin will fix for now.
Resolves #1125.
=> Temporary pin: numpy<1.24

examples/ipynbtests.sh
Something recently broke in the download of results that are used in the notebook tests.
TBH, I should probably move that into a git repo or something, instead of keeping them in my personal Dropbox. The use of my personal Dropbox for this probably predates the existence of an OpenPathSampling organization on GitHub, and (except few times I was stupid enough to move those files), it's never really caused us problems. But still. Not best practice.
=> Fix Dropbox download of precalculated results

.github/workflows/check-openmm-rc.yml, .github/workflows/test-openmm-rc.yml
Some change has caused the token for workflow dispatch (the mechanism we used to conditionally launch a workflow) to fail. However, in the meantime, GitHub has added a native approach for reusing workflows. So this is intended to switch to using that.
And we're probably going to have some things to change thanks to the OpenMM 8.0 release candidate....
=> Fix testing against OpenMM RCs

openpathsampling/experimental/simstore/sql_backend.py, openpathsampling/experimental/simstore/test_attribute_handlers.py, openpathsampling/experimental/simstore/test_callable_codec.py, openpathsampling/experimental/simstore/test_class_info.py, openpathsampling/experimental/simstore/test_custom_json.py, openpathsampling/experimental/simstore/test_dict_serialization_helpers.py, openpathsampling/experimental/simstore/test_serialization.py, openpathsampling/experimental/simstore/test_sql_backend.py, openpathsampling/experimental/simstore/test_storable_function.py, openpathsampling/experimental/simstore/test_storable_function_integration.py, openpathsampling/experimental/simstore/test_storage.py, openpathsampling/experimental/simstore/test_tags_table.py, openpathsampling/experimental/simstore/test_tools.py, openpathsampling/experimental/simstore/test_type_ident.py, openpathsampling/experimental/simstore/test_utils.py
SQLAlchemy 2.0 has been released, and SimStore tests are failing now. There were warnings in 1.4 that help migrate to the 2.0 API. This implements those changes.
Still have a couple places where I want to manually check the SQL output to ensure that this is the same, but this PR will fix current errors.
=> Updates for SQLAlchemy 2.0

.github/workflows/tests.yml, examples/tests/test_openmm_integration.ipynb, openpathsampling/engines/external_engine.py, openpathsampling/tests/test_gromacs_engine.py
Taking a few days to do some OPS upkeep; after far too much neglect. This PR will get our tests back in working order.
Importantly, as of this PR (and the next release), we're (finally) dropping Python 2.7 support. It is too much of a maintenance burden, and everyone else dropped it over 3 years ago. There should be no active projects going with Python 2.7.
=> Get tests working again

.github/workflows/tests.yml, examples/ipynbtests.sh, openpathsampling/deprecations.py, openpathsampling/experimental/simstore/callable_codec.py, openpathsampling/experimental/simstore/test_callable_codec.py, openpathsampling/netcdfplus/dictify.py, setup.cfg
This is a follow-up on #1132, and should only be merged after that one.
This PR will bring OPS tests in line with the [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) guidance on Python version support: namely, we will drop anything before 3.9, and support everything after 3.9 that is also supported by released versions of our major dependencies (typically involved waiting on support in the OpenMM ecosystem to filter through).
To-do:
Due to major changes in opcodes in Python 3.11, we're using SimStore's `CallableCodec` to serialize callables in Python 3.11, even in netcdfplus storage. This has the side effect that we needed to change the `CallableCodec`'s output to be base64-encoded so that it was serializable by `ujson` (SimStore's JSON codec ecosystem knows how to store …
=> Support Python 3.10; Python 3.11

setup.cfg
I'm not sure why we're just now picking up nbval 0.10.0 (released in January), but it seems to be causing tests to fail.
=> Pin nbval != 0.10.0

openpathsampling/engines/openmm/engine.py
In OpenMM 8.1, it seems that we must pass `None` for engine properties. The empty dict is no longer treated the same.
=> Fix engine props for OpenMM 8.1

examples/tests/test_netcdfplus.ipynb, examples/tests/test_openmm_integration.ipynb, openpathsampling/experimental/storage/test_collective_variables.py, openpathsampling/experimental/storage/test_mdtraj_json.py, openpathsampling/experimental/storage/test_simtk_unit.py, openpathsampling/experimental/storage/test_snapshots_table.py, openpathsampling/tests/test_spring_shooting.py
In #1123, most of our setup/teardown methods were fixed to use pytest's preferred (and now required) `setup_method`/`teardown_method` nomenclature. This fixes a few more.
---
**UPDATE**: This fixes 3 problems caused by upstream breaking changes:
1. As mentioned above, pytest now requires `setup_method` / `teardown_method` instead of `setup` and `teardown`.
2. Newer versions of pytest only work with nbval 0.10.0 or later. nbval 0.10.0 introduced what I consider to be a bug, which is that return values that you hide in-notebook with a `;` are seen by nbval as output. This required using `NBVAL_IGNORE` in some notebooks.
3. pytest also broke XUnit-style tests that include staticmethods as tests (I consider this to also be a bug). The fix was to just make them instance methods.
=> Fix a few more setup -> setup_method tests

.github/workflows/test-openmm-rc.yml
Our script to test OpenMM RCs was pinned to Python 3.9, which we no longer support. Looks like there's another OpenMM RC out, so it is time to update this!!
=> Update Python version in test-openmm-rc

openpathsampling/shooting.py, openpathsampling/tests/test_shooting.py
This adds a volume-based shooting point selector. It will only select points from a given volume.
(I thought we already had this? I thought this was implemented as part of "Shooting Range" by @hejung in one of our ESDWs? Guess that code never made it into main. Not too hard to recreate this much of it, though.)
=> Volume shooting point selector

openpathsampling/experimental/simstore/sql_backend.py
This looks like a SQLAlchemy 2.0 issue that isn't covered in the current unit tests, but is covered in some more extensive external tests.
=> Fix `SQLStorageBackend.load_storable_function_table`

openpathsampling/analysis/path_histogram.py
This adds a touch point for path density histogram subclasses to change what occurs when adding an OPS trajectory to a PathDensityHistogram.
I needed this when playing with the idea of having a custom histogram that would also track all trajectories that passed through a given histogram bin.
This doesn't break the API, and doesn't even need changes in the tests.
=> Custom `PathDensityHistogram._add_ops_trajectory`

openpathsampling/ensemble.py
Long ago, we tried to use the string representations of ensembles as the comparison for equality. This was a decent idea, although there are some issues with the ways we handle equality and hashing.
I recently came across a weird edge case where a periodic volume with an edge exactly at -pi was serialized in 2 different ways: one with the edge at -pi and one with the edge at +pi. I'd still like to look into what happened to make that happen, but this would fix the most obvious effect (which is that the resulting ensembles weren't equal). In any case, this is a good shortcut: the same UUID indicates the same object, assuming we can trust the meaning of UUID.
=> Let UUID determine equality for ensembles

openpathsampling/experimental/simstore/callable_codec.py, openpathsampling/experimental/simstore/class_info.py, openpathsampling/experimental/simstore/class_lookup.py, openpathsampling/experimental/simstore/custom_json.py, openpathsampling/experimental/simstore/serialization_helpers.py, openpathsampling/experimental/simstore/sql_backend.py, openpathsampling/experimental/simstore/storable_functions.py, openpathsampling/experimental/simstore/test_serialization_helpers.py, openpathsampling/experimental/simstore/test_uuids.py, openpathsampling/experimental/simstore/type_ident.py, openpathsampling/experimental/storage/monkey_patches.py
This includes several performance improvements and minor fixes for SimStore. Quick manifest:
* Added and started using `is_storage_string` and `has_storage_uuid`, which use the fast `ClassIsSomething` model to cache classes with given attributes. The normal `is_string` and `has_uuid` methods were taking a larger fraction of time than they should.
* Added default support for SQL index on UUID (which should have been there all along).
* Fix an edge case where old-style CVs were no reloaded correctly in SimStore, because the new JSON serialization was already making a callable and the code to make a callable from the marshal data was no longer needed.
This also helps clear up some of the external testing in ops-storage-notebooks which has been off for a while.
=> SimStore performance improvements and fixes

.github/workflows/deploy_docs.yml, .github/workflows/tests.yml
Mambaforge has been deprecated. See https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/
Now miniforge is effectively identical to the old mambaforge. At the same time, I'm updating the version action we're using.
=> Update to use setup-miniconda v3; use miniforge

docs/developers/engines.rst, docs/developers/engines_trajectory_export.rst, openpathsampling/collectivevariable.py, openpathsampling/collectivevariables/plumed_wrapper.py, openpathsampling/engines/dynamics_engine.py, openpathsampling/exports/trajectories/__init__.py, openpathsampling/exports/trajectories/core.py, openpathsampling/tests/exports/trajectories/test_core.py, openpathsampling/tests/test_dynamicsengine.py, openpathsampling/tests/test_external_engine.py, openpathsampling/tests/test_pathmover.py
One of the major things that came out of the path sampling software meeting in Leiden in September 2024 was a desire for OPS to export trajectories more easily into formats that people are more familiar with.
In this PR, I'm starting to add functionality for external trajectory export. The eventual goal is that you'll be able to export a trajectory using `engine.export_trajectory(trajectory, filename)`. That method will take an optional `writer` parameter that takes a callable to perform the actual output. This allows a single unified interface from the user perspective, but allows individual callable (as, e.g., instances of a class) to handle details of implementation; for example, allowing lossy output while defaulting to lossless. Different engines can also have different default …
=> Trajectory Exports: Core and integration in `DynamicsEngine`

.gitignore, openpathsampling/engines/gromacs/engine.py, openpathsampling/engines/openmm/engine.py, openpathsampling/exports/trajectories/__init__.py, openpathsampling/exports/trajectories/core.py, openpathsampling/exports/trajectories/mdtrajtrajectorywriter.py, openpathsampling/exports/trajectories/trrtrajectorywriter.py, openpathsampling/tests/exports/trajectories/conftest.py, openpathsampling/tests/exports/trajectories/test_core.py, openpathsampling/tests/exports/trajectories/test_mdtrajtrajectorywriter.py, openpathsampling/tests/exports/trajectories/test_trrtrajectorywriter.py, openpathsampling/tests/test_gromacs_engine.py, openpathsampling/tests/test_openmm_engine.py
Add support in OpenMM and Gromacs engines to export trajectories. This includes lossless export (as TRR) and lossy export (via MDTraj, where the export format will be determined from the filename). We use TRR format as the default lossless format for both OpenMM and Gromacs.
Overall plan:
* Add support for core functionality and defaults for SimStore exports. (#1170)
* **This PR**: Add support for TRR export for Gromacs and OpenMM engines (as defaults for those engines). Add support for MDTraj-based export for lossy exports.
* Later PR: Add support to export a list of MCSteps, using a given TrajectoryWriter and some definition of where to store step information.
* Later PR: Add new type of storage (based on SimStore) that uses lossless external trajectory storage for snapshot data …
=> Trajectory Exports: MDTraj and TRR formats; Gromacs and OpenMM support

examples/tests/test_cv.ipynb, examples/tests/test_netcdfplus.ipynb, examples/tests/test_openmm_integration.ipynb, setup.cfg
We pinned numpy to <2 while numpy 2 was in RC mode on testpypi because I was trying to release OPS 1.6.1, and MDTraj wasn't ready for numpy 2 yet. It's been a while. Let's release that pin. I'm hoping this will help make it easier to clean up some of the notebook tests.
=> Drop numpy pin
