openpathsampling/openpathsampling

.travis.yml, devtools/ci/after_sucess.sh, devtools/ci/push-docs-to-s3.py
This should fix the automatic redirection from http://openpathsampling.org
=> Push to S3 now pushes to latest/ folder

README.md, devtools/ci/after_sucess.sh
A tiny update to README.md to see if Travis likes this or not. See problems in #124.
=> Trivial PR

.travis.yml, devtools/ci/after_sucess.sh, docs/readme.rst, docs/sphinxext/pandoc_sphinxext.py
Checking what is wrong with markdown conversion to enable adding Davids Examples!
=> Add Pandoc Markdown support

devtools/ci/ipythontests.sh, devtools/ci/nosetests.sh, openpathsampling/pathmover.py, openpathsampling/tests/test_helpers.py, openpathsampling/tests/testpathmover.py, openpathsampling/tests/teststorage.py
Added output to test that has been giving us trouble lately, per https://github.com/choderalab/openpathsampling/issues/138#issuecomment-73869458
=> Storage test debug

openpathsampling/snapshot.py, openpathsampling/topology.py, openpathsampling/trajectory.py
One of the things to do in #153 so that we have consistent and clear code.
=> Rename atoms to n_atoms

devtools/ci/install.sh
Resolves #173 
Quick fix here to be merged in so it can be merged into all branches.
=> Switch conda to https following JHP's fix

openpathsampling/storage/object_storage.py
This removes an unnecessary logging that slows down loading from storage.
=> removed slowing debug logging

openpathsampling/__init__.py, openpathsampling/ensemble.py, openpathsampling/tests/testensemble.py, openpathsampling/tests/testpathmover.py, openpathsampling/volume.py
Makes TISEnsemble into a full-fledged class instead of factory function. This allows us to store some extra info in it, which will make analysis easier (and will make it easier to create modified versions of the ensembles if we want to change things, like remove a given state from the allowed final states).
=> TISEnsemble as a separate class

openpathsampling/storage/cv_store.py, openpathsampling/storage/object_storage.py, openpathsampling/storage/snapshot_store.py, openpathsampling/storage/storage.py, openpathsampling/storage/trajectory_store.py
remove unnecessary syncing
allow None in object.save
=> allow None storage in object.save and remove sync

openpathsampling/trajectory.py
trajectory correlation uses configurations now
=> fix decorrelation

openpathsampling/storage/sample_store.py
This should do the trick. Tested the toy_analysis.ipynb and it works now and is fast.
Let's see if the tests pass.
=> Fix incorrect fast caching of samples

docs/api.rst, docs/collectivevariable.rst, docs/engine.rst, docs/ensemble.rst, docs/examples/mstis.rst, docs/getting_started.rst, docs/index.rst, docs/pathmover.rst, docs/pathsimulator.rst, openpathsampling/collectivevariable.py, openpathsampling/pathmovechange.py, openpathsampling/pathmover.py, openpathsampling/storage/object_storage.py, openpathsampling/todict.py, openpathsampling/treelogic.py
A few rephrasings, and added the MSTIS example ipynbs, but this mostly consists of minor fixes to stop most of the complaints sphinx had while building the docs.
Merge at will.
=> Docs fixes

devtools/ci/ipythontests.sh
Just what it says in the headline. Should have done this as part of #291. Merge at will.
=> Add MISTIS analysis to tests

openpathsampling/sample.py, openpathsampling/tests/testsample.py
Resolves #315. Ready for review and merge as soon as it passes tests.
=> Clearer error message for sanity check

devtools/ci/requirements-conda-2.7.txt, examples/ipython/ipynbtest.py
Add support for Jupyter / IPython 4.0.0 (ala "the big split") and add a few little improvements to the ipynbtester...
=> Jupyter support

openpathsampling/visualize.py
=> fix font_color bug

examples/ipython/README.md
Small updates to remove files from the manifest that are no longer in the directory, and to include a pointer to http://github.com/jhprinz/ipynb-test.
=> Updates to the examples/ipython/README.md

openpathsampling/analysis/tis_analysis.py
Some cleanup of rate analysis, mostly adding logging. See #390.
Ready for merge as soon as it passes tests.
=> Analysis logging

devtools/conda-recipe/meta.yaml, docs/getting_started.rst
Just adding a little more to the docs for installing. I've been telling people that OPS is ready for them to look at; it would probably help if the docs gave accurate instructions on how to install.
Ready to merge. Only changes are in docs.
=> Updates to the install process

.travis.yml, devtools/ci/git_hash.sh, openpathsampling/__init__.py
Resolves #417. If the installation includes `version.py`, this imports it.
=> Include `version` in `__init__.py`

examples/ipython/README.md, examples/ipython/simple_fixed_length_tps.ipynb, openpathsampling/__init__.py, openpathsampling/analysis/network.py, openpathsampling/analysis/tis_analysis.py, openpathsampling/tests/test_helpers.py, openpathsampling/tests/testnetwork.py, openpathsampling/tests/testtransitions.py
Answering @jchodera’s request for fixed path length TPS. See https://github.com/choderalab/openpathsampling/pull/467#issuecomment-211494315 ff.
In the process, this should also do a little to clean up the approach currently used in TPS transitions and networks, to make it easier to re-use code.
=> Fixed length TPS

examples/ipython/test_netcdfplus.ipynb
This should fix the problem with the test in cell 73 and closes issue #475.
=> Fix dict order in `test_netcdfplus.ipynb`

openpathsampling/engines/openmm/engine.py, openpathsampling/tests/testopenmmengine.py
Ready for review and merge
This closes issue #483 .
Also adds a test.
=> fix setting box_vectors

openpathsampling/analysis/move_scheme.py
Bug introduced by #386, caught while working on [OPSPiggybacker](https://github.com/dwhswenson/OPSPiggybacker)
=> Fix bug in LockedMoveScheme storage

.travis.yml, openpathsampling/tools.py
This should be a general problem changing to conda-build 2.0. They changed the name of the test environment from `test` to `t_env`. Hope this is a quick fix
=> fix conda-build 2.0 problems

openpathsampling/engines/features/kinetics.py, openpathsampling/engines/features/statics.py, openpathsampling/engines/snapshot.py, openpathsampling/tests/test_features.py
Addresses #580. 
As discussed with @dwhswenson . Ready to be reviewed
=> Implement `Copy_with_replacements`

devtools/conda-recipe/meta.yaml, devtools/conda-recipe/requirements.txt
=> Fix build incompatibility between matplotlib and Qt

devtools/conda-recipe/meta.yaml, devtools/conda-recipe/requirements.txt, examples/ipython/test_netcdfplus.ipynb, openpathsampling/netcdfplus/dictify.py, openpathsampling/netcdfplus/objects.py, openpathsampling/tools.py, openpathsampling/visualize.py, setup.py, setup.yaml
ujson is a (MUCH!) faster implementation than using pyyaml. This should give a big speed bump when loading objects.
=> Simple replacement of json and pyyaml by ujson

devtools/conda-recipe/meta.yaml, setup.py, setup.yaml
Title says it all. In preparation for release 0.9.1.
=> 0.9.0 => 0.9.1 everywhere I could find it

openpathsampling/netcdfplus/objects.py
=> fix using -1 in getitem for stores

openpathsampling/engines/openmm/tools.py, openpathsampling/engines/trajectory.py, openpathsampling/tests/test_mdtraj_support.py
Resolves #613.
(In progress until I do a test for it)
=> Fix for to_mdtraj missing box vectors

examples/misc/tutorial_pathtree_visualization.ipynb
@sroet Should exmplain how to change the CSS that sets the width of the connectors.
=> Add example to connector thickness

docs/examples/miscellaneous/committors.rst, docs/examples/miscellaneous/committors_alanine_dipeptide.rst, examples/misc/README.md, examples/misc/alanine_dipeptide_committor/1_select_snapshots.ipynb, examples/misc/alanine_dipeptide_committor/2_committor_simulation.ipynb, examples/misc/alanine_dipeptide_committor/3_committor_analysis.ipynb, examples/misc/alanine_dipeptide_committor/4_analysis_help.ipynb, examples/misc/alanine_dipeptide_committor/README.md
Another example of using the committor analysis. Wanted to put this into the official OPS docs. It's based on an (abandoned) project with some machine learning people, so a few parts of it are done in a slightly odd way (treating each shot as an "experiment").
The original work from this was in [a gist](https://gist.github.com/dwhswenson/e1578a40ef67aae66da15e7b065c8f7c). I'd rather put it in the OPS docs and link to it here as an example for my E-CAM module about the committor analysis.
No code, only docs, so should be easy to merge. Can be merged before or after the 0.9.2 release.
=> AD committor example

.travis.yml, devtools/conda-recipe/meta.yaml, devtools/conda-recipe/requirements.txt
Playing around to see if I can identify the source of the problem @jhprinz was having in https://github.com/openpathsampling/openpathsampling/pull/636#issuecomment-272648678 (see also the [Travis run](https://travis-ci.org/openpathsampling/openpathsampling/builds/191969082)). We're also having this in the nightlies.
=> Testing to fix Travis error

openpathsampling/ensemble.py, openpathsampling/high_level/interface_set.py, openpathsampling/high_level/network.py, openpathsampling/high_level/transition.py, openpathsampling/pathmover.py
Mostly cleaning up extraneous spaces and little PEP8 mistakes.
Merge at will. This is just intended to make review of future PRs easier by separating the cleanup from the real code. There's plenty more style cleanup to do, but this improves a few files that I plan to work on the in the near future.
=> Style cleanup

.travis.yml, devtools/conda-recipe/build.sh, devtools/conda-recipe/meta.yaml, devtools/conda-recipe/requirements.txt, setup.py, setup.yaml
There is some legacy requirements of packages not needed anymore.
Remove
```
pyyaml
pymbar  # might be added in the future again
docopt  # was never used
```
=> Remove unused requirements

devtools/conda-recipe/meta.yaml, devtools/conda-recipe/requirements.txt
Unpinning this in #677 seems to be causing problems in unexpected places: build (but not tests), downstream code, and sphinx docs building.
Hoping this fixes those.
=> Pin hdf4=4.2.12

.travis.yml, openpathsampling/engines/openmm/engine.py, openpathsampling/engines/trajectory.py, openpathsampling/netcdfplus/dictify.py, openpathsampling/netcdfplus/netcdfplus.py, openpathsampling/visualize.py
More python 3 compatibility fixes
=> [Py3-compatibility] fix some iteritems and use of long

.travis.yml
Not sure, but I think, the problem is a misconfigured .travis.yml file not missing keys. Turns out that the keys are not set in the current script. This might fix it. Hard to test.
=> Fix encryption keys

openpathsampling/netcdfplus/attribute.py, openpathsampling/netcdfplus/dictify.py
=> Add better comparison for PseudoAttribute.__eq__ that works with Python 3

openpathsampling/netcdfplus/attribute.py, openpathsampling/netcdfplus/dictify.py
Resolves #734 .
First attempt. @dwhswenson Can you confirm that this fixes the issue?
=> Fix base64 decodebytes

.travis.yml
Previous fix (#742) did not fix at all. Trying again, based on https://github.com/travis-ci/travis-ci/issues/8934.
=> Another attempt to fix Travis

docs/Makefile, docs/_static/ipynb.css, docs/conf.py, docs/sphinxext/ipynb.css, docs/sphinxext/notebook_sphinxext.py
This just fixes the use of some CSS. It has always been there but was not used. This add the correct file and uses it.
=> fix ipynb CSS style in RTD Sphinx theme

openpathsampling/netcdfplus/netcdfplus.py
=> Only keep existing value stores in attribute_list

docs/topics/simulation_setup.rst
This has been promised as "coming soon" in the docs for a while. It was implemented in #750, which was merged a long time ago.
This PR just adds a quick update to show how one would use this, as part of the simulation setup topic docs.
Docs only; if no review in 2 days, I'll self-merge (22 August).
=> Add docs on getting velocities from a file

.travis.yml, devtools/conda-recipe/meta.yaml, devtools/install_recipe_requirements.py, devtools/optional_packages.txt, devtools/testing_requirements.txt
This is a (temporary) fix for #812.
=> Pin libnetcdf to 4.6.1; update install process

openpathsampling/shooting.py, openpathsampling/tests/test_shooting.py
A small PR to add missing tests for shooting point selectors (and to touch up some *very* old code).
=> Shooting selector tests

.travis.yml, devtools/ci/after_sucess.sh, docs/_templates/layout.html, docs/conf.py, docs/developers/index.rst, docs/index.rst, docs/openpathsampling.bib, docs/readme.rst, docs/requirements.txt, docs/shooting.rst, docs/snapshot_modifiers.rst, openpathsampling/numerics/histogram.py, openpathsampling/numerics/wham.py, openpathsampling/pathmover.py, openpathsampling/shooting.py
Something in the simplified Travis installation procedure from #840 seems to have broken our doc-building stage. This PR will fix that, and also make a few other minor improvements in the docs.
Updates to include:
=> Fix docs build

openpathsampling/engines/openmm/engine.py
Changes to the docstring to reflect current implementation.
(Maintainer edit: closes #769)
=> updated OpenMMEngine docstring, adresses #769

openpathsampling/netcdfplus/dictify.py
func_name is not an attribute of FunctionCV
=> fix bug when getting the name of the function used to define the cv

.travis.yml, openpathsampling/analysis/shooting_point_analysis.py, openpathsampling/tests/test_shooting_point_analysis.py
This adds progress indicators (i.e., tqdm support; introduced in #882) for the shooting point analysis. With tqdm installed, you automatically get progress bars when doing the analysis.
=> Progress indicator for shooting point analysis

devtools/ci/miniconda_install.sh
This has already solved problems on a couple other of my repos, so I'll merge this here as soon as it passes.
=> Fix miniconda install

openpathsampling/tests/test_progress.py
=> make tqdm optional for tests

docs/cli.rst
This just makes a few fixes to the docs for the CLI. Since it is a small docs-only change, I'll merge this as soon as it passes.
=> Minor improvements on CLI docs

openpathsampling/tests/test_volume.py, openpathsampling/volume.py
A recurring issue has been that users create CVs that return length-1 arrays/lists, and then use these CVs to define volumes/interfaces. Because Python/NumPy allow order comparisons on length-1 iterables as if they were scalars, sampling goes fine. However, some aspects of analysis expect the CVs to output scalars, and then users get cryptic error messages at unexpected points.
This PR emits a warning if the CV used by a `CVDefinedVolume` returns an iterable.
See also #1029.
=> Warn if CVDefinedVolume CVs return iterables

openpathsampling/pathsimulators/path_sampling.py, openpathsampling/tests/pathsimulators/test_hooks.py
=> Fix bug in live visualizer setup with implicit hooks

openpathsampling/engines/openmm/engine.py
Resolves #817
I looked through the issues I opened and realized that this one is a real low hanging fruit :)
=> Fix OpenMM engine docs on n_frames_max

openpathsampling/netcdfplus/version.py, setup.cfg
Will merge immediately after tests pass.
=> Bump version to 1.5.3.dev0

openpathsampling/tests/test_volume.py, openpathsampling/volume.py
while looking at the correctness of the docstring in #1068 I noticed a tiny bug in CVDefinedVolume.
fixed bug in 8ea8d38
added test in 11c4119
dropped nose from test_volume.py in 41ffb9b
=> Actually check for CVDefinedVolume.lambda_max == "inf"

openpathsampling/integration_tools.py
See https://mattermodeling.stackexchange.com/q/9770
=> clarify error message on missing units

.github/workflows/tests.yml, codecov.yml
Looks like PRs aren't running coverage tests; hoping this will fix.
=> Update to CodeCov v4 (using CODECOV_TOKEN secret)
